### ISSUE TITLE
Markdown syntax highlighting broken

### ISSUE THREAD

**Issue by benweier** [ctf0/Seti_ST3#100]
Markdown highlighting has been broken for a while in all Seti UI colour schemes. The Seti UX scheme appears to be working though.

![image](https://cloud.githubusercontent.com/assets/814402/6222606/7b60fb48-b6a2-11e4-9162-d6c11bd11bfb.png)

**Comment by ctf0** [comment]
both `Seti_orig & Seti_monokai` dont have enough support for md but `Seti` does ,and `Seti_UX` have the most of them all because thats what i mostly use.

**Comment by ctf0** [comment]
support added to the latest release.
