### ISSUE TITLE
A way to de-activate the syntaxes

### ISSUE THREAD

**Issue by GoOz** [ctf0/Seti_ST3#101]
Seti_UI is a really cool theme but i don't need the syntaxes it comes with. I prefer choosing my own syntaxes, installed on their own.
The thing is, i don't know exactly why but, Seti syntaxes takes over my own. "View/Syntax/Open all with" option doesn't change a thing. It's always Seti's syntaxes by default.
I couldn't find any other way than delete the concerned tmLanguage files which is not what i can call a durable solution. Is there a good solution for that?

**Comment by ctf0** [comment]
i haven't encountered on my machine ,but anyway unfortunately there is no solution i can think of atm.
