### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by eorroe** [ctf0/Seti_ST3#103]
Every time there's an update. I have to lookup the package in package control to copy the settings for the theme and color scheme. Or lookup it up through the folder.

Basically every time there's an update. Sublime goes back to original color_scheme and theme.

Anyway to fix this?

**Comment by ctf0** [comment]
thats because on each update like an other package ,PC ignores that package then after installing the new update it re-enables it but as this is a theme u will need to restart ST for it to re-apply properly.

**Comment by eorroe** [comment]
I don't want to open another issue, but what **exact color scheme** is the one in the picture:

For me the one under the settings is not those exact colors:
![Image of Sublime](https://raw.githubusercontent.com/ctf0/Seti_ST3/master/+res/screenshot-1.png)

**Comment by eorroe** [comment]
Ok

**Comment by akloeber** [comment]
@ctf0: I have this issue too. In the user preferences `theme` magically switches back to `Default.sublime-theme` but `Seti.sublime-theme` does not get "re-applied" automatically after restarting as you mentioned. I have to manually set `"theme": "Seti.sublime-theme"` in user prefs and restart afterwards.

**Comment by ctf0** [comment]
@akloeber on both windows and osx i dont have ur issue, can u try clean install and see what u get ??

**Comment by akloeber** [comment]
@ctf0: I'm on Mac OS X too running latest ST3 (Build 3083). With "clean install" do you mean uninstallation and re-installation of Seti through Package Control?

**Comment by akloeber** [comment]
I reinstalled Seti, so let's see if it works when the next update arrives...

**Comment by akloeber** [comment]
@ctf0: v8.4 arrived and now everything worked as you described. Also the following dialog appeared which I thing was not the case with previous updates:
![bildschirmfoto 2015-05-31 um 19 27 10](https://cloud.githubusercontent.com/assets/968308/7902933/b887d012-07cb-11e5-9689-eeb29399dd86.png)

**Comment by ctf0** [comment]
@akloeber this msg should come up with each update, which is an indicator that everything is good also now u dont need to restart st after the update, the app will apply the update for u automatically.

**Comment by akloeber** [comment]
@ctf0: Well, I actually had to restart in order to reactivate the Seti themed sidebar again after this dialog appeared. Should that not be neccessary?

**Comment by ctf0** [comment]
well sometimes u need to restart and sometimes u don't, depends on the version of ST.
