### ISSUE TITLE
Color Scheme Problem

### ISSUE THREAD

**Issue by eorroe** [ctf0/Seti_ST3#106]
Color Scheme settings go back to default whenever there's an update.

Meaning I had changed the color scheme settings around a bit, once this package updated. I pretty much lost all my color scheme changes (took a while).

Or am I missing something here. Is that how sublime text works and I'm suppose to save to a separate file or something?

**Comment by ctf0** [comment]
if u change the color scheme u shouldnt directly change the one in the package ,instead copy this file to `Packages/Theme - Default` and do ur changes in there ,but keep in mind that u will need to merge any new changes to that file.

**Comment by eorroe** [comment]
I just created a new file called `mySeti.tmTheme` thanks.
