### ISSUE TITLE
Search text not vertically centered (minor graphic detail)

### ISSUE THREAD

**Issue by samedii** [ctf0/Seti_ST3#107]
![image](https://cloud.githubusercontent.com/assets/1872050/6537709/d2e16f0a-c459-11e4-8867-c9ceae513f51.png)

Would look lovely if it was centered better. I have a feeling this might be something that cannot be fixed though. Great theme overall!

**Comment by ctf0** [comment]
this is because of the line height/padding ,check the `"Seti_pad_5": true,` or `"Seti_pad_3": true,`

**Comment by samedii** [comment]
Using Seti_pad_0 looks better but it's not centered unless i use "line_padding_top": 5 which makes everything else (except the search bar) look really bad.

Seems it's not possible to set different line paddings for different parts of the ui?

**Comment by ctf0** [comment]
there is no `pad_0` its either `3 or 5` and so the line padding should be either `0,3 or 5` also when u use the line_padding option make sure to use both top & bottom or u will get a wierd margins.

note that the line_padding option effects everything and not just the search bar ,this is a limitation of ST so u either have the same margin/padding everywhere or u dont also everywhere.

**Comment by samedii** [comment]
Weird because it looks like this for me

![image](https://cloud.githubusercontent.com/assets/1872050/6540844/30662166-c4b4-11e4-9e07-377bc49ccd6b.png)

**Comment by ctf0** [comment]
oh btw u should try to resize the search bar it self as it doesn't resets automatically.

**Comment by samedii** [comment]
I can make it larger by resizing but it can't get smaller

**Comment by ctf0** [comment]
am sorry but beyond what i've mentioned i cant help u :(.

**Comment by samedii** [comment]
Thanks for trying it's not that important :) Great theme!
