### ISSUE TITLE
Sidebar problems

### ISSUE THREAD

**Issue by samedii** [ctf0/Seti_ST3#108]
Problems with overlapping in the sidebar
![image](https://cloud.githubusercontent.com/assets/1872050/6571320/551ad65a-c707-11e4-90dd-c5d9312ebd42.png)

Also if I switch between projects (or when i first show the sidebar maybe?) the sidebar is empty but it comes alive if I press "alt" to show the menu
![image](https://cloud.githubusercontent.com/assets/1872050/6571334/9e157e0a-c707-11e4-93c9-88c4c40df5a3.png)

I thought these might be related so I posted them together

**Comment by samedii** [comment]
I'm having these problems on windows. You can get my setup by standing in
C:\Users\<username>\AppData\Roaming\Sublime Text 3\

and cloning https://github.com/samedii/sublime into .

**Comment by ctf0** [comment]
i dont know what exactly is the problem but its working fine in here ,send me the settings u have in ur user prefs.

**Comment by samedii** [comment]
I did https://github.com/samedii/sublime/blob/master/Packages/User/Preferences.sublime-settings

**Comment by ctf0** [comment]
check https://github.com/ctf0/Seti_ST3/issues/88#issuecomment-77972798

**Comment by samedii** [comment]
I think that fixed it, big thanks! :+1:
