### ISSUE TITLE
Implement Yeti theme

### ISSUE THREAD

**Issue by wldcordeiro** [ctf0/Seti_ST3#109]
Seti has a light color twin called Yeti, it'd be kind of cool to do a port of that too? https://atom.io/themes/yeti-ui

**Comment by ctf0** [comment]
for quite some time now and i was thinking about porting it but kinda lazy.

**Comment by kristofferahl** [comment]
+1. Love Seti but always preferred a light colored theme.

**Comment by victorwpbastos** [comment]
That would be really awesome! :heart_eyes:

**Comment by ctf0** [comment]
if someone would like to port it ,plz do and i will answer any question u may have.

**Comment by emadb** [comment]
+1 
Where can I find documentation on how to modify your theme? I know nothing about "ST theming", but I can try to create a light Seti UI theme. Just give me a starting point.

**Comment by ctf0** [comment]
@emadb sadly i haven't found any,i simply gathered the themes that have what i want and with try and error i made Seti.

**Comment by ctf0** [comment]
The theme is almost done, i just need someone to work on the scheme , and if possible i would highly appreciate if someone can re-port the scheme for Seti as-well as the current one is a big mess.
