### ISSUE TITLE
Fix update dialog

### ISSUE THREAD

**Issue by Chris54721** [ctf0/Seti_ST3#110]
The Sublime Text update dialog currently looks like this:
![1426108675](https://cloud.githubusercontent.com/assets/3685659/6607098/8744891a-c83c-11e4-8adf-6ecec001193e.png)

**Comment by ctf0** [comment]
on Win7 & OSX 10.9.x+ all are good ,i don't know what could have caused that.

**Comment by Chris54721** [comment]
Looks the same on OSX 10.10.x with the theme as the only plugin.
I'm using dev builds (http://sublimetext.com/3dev) so it's probably a change in the latest ones.
![1426429634](https://cloud.githubusercontent.com/assets/3685659/6656357/e453c1d2-cb27-11e4-9f48-e954e84e547a.png)

**Comment by pupaxxo** [comment]
![image](https://cloud.githubusercontent.com/assets/2815664/6656401/2e1b62fa-cb2a-11e4-9c69-c6f0a960cb21.png)
Same problem here.

**Comment by ctf0** [comment]
oh okey ,after more investigation am having the same issue ,the theme have nothing to do with the font color in the main app notifications ,i have no solution for that am sorry.

**Comment by Chris54721** [comment]
Can't you change the background color? Other themes do that, e.g. https://github.com/thinkpixellab/flatland/blob/master/Flatland%20Dark.sublime-theme
![1426430878](https://cloud.githubusercontent.com/assets/3685659/6656423/d7830f46-cb2a-11e4-9d45-f9ba11d2bc32.png)

**Comment by Chris54721** [comment]
I think I just found the solution.
In `Seti.sublime-theme`:
```
{
  "class": "dialog",
  "layer0.tint": [238, 238, 238],
  "layer0.opacity": 1
}
```

RGB(238, 238, 238) = #EEE (almost white)
Changing that changes the dialog background.

**Comment by ctf0** [comment]
@Chris54721 play with the value till u find something that suites ur need and send me a PR.

**Comment by Chris54721** [comment]
Pull Request #112
