### ISSUE TITLE
can you give an option to change the font name and size on sidebar?

### ISSUE THREAD

**Issue by ysfjwd** [ctf0/Seti_ST3#115]
I use Fira Mono as a font, and gets irrated when the sidebar text is not of the same size or same font.
Can this option be provided as part of the theme, because updates come fast, and everytime there is an update, I had to change the theme file which gets over written

**Comment by ctf0** [comment]
the theme doesnt have any option that effects the fonts used ,the only way to change the font is through the user pref settings.

**Comment by ysfjwd** [comment]
it is actually in the theme file, see this thread for reference

http://superuser.com/questions/748381/sublime-text-3-sidebar-font-face-change

and everytime the theme gets updated, have to manually change it :)

**Comment by ctf0** [comment]
the theme in the link u mentioned ,yes it have that option ,but in Seti there is no such a setting ,so basically u just set one font and it will be applied everywhere ,unless this is not what u want and u r looking to have the same functionally as the one u mentioned.

**Comment by ysfjwd** [comment]
in file `Seti.sublime-theme` at line 596, i just do this after every update

```
	// Sidebar files
	{
		"class": "sidebar_label",
		"font.face": "TheSansMono",
		"font.size": 13
	},
```

and sidebar font and size changes :). can this be built into theme, i don't know much about theming, otherwise i would pushed a pull request.

**Comment by ctf0** [comment]
i will try to add it later.

**Comment by ysfjwd** [comment]
thankyou :dancer:

**Comment by Ardakilic** [comment]
Afterglow theme does it, it'd be an example for how they are doing it.

https://github.com/YabataDesign/afterglow-theme

**Comment by ctf0** [comment]
@Ardakilic the options in the Afterglow theme are for font size but what @ysfjwd is after is to have a different font for the sidebar other than the one used in the whole app.

**Comment by ysfjwd** [comment]
although i don't know much about theming, but my initial homework gives me the impression that theme only understands variables in settings file which are either true or false. you cannot give a custom value.

for example in the sublime theme file,

```js
// Sidebar entry font size 12
    {
        "class": "sidebar_label",
        "settings": ["sidebar_size_12"],
        "font.size": 12,
        "color": [116, 116, 116] // 03
    }
```

the "settings" value tells the theme to look for the value "sidebar_size_12" in user settings file, if found, and set to ```true```, set the ```"font.size": 12```

you cannot set the "font.size" value to value in settings.py. This is my initial impression, but i am working on it to see if a variable for user settings file can have a value other than ```true``` or ```false```

**Comment by ctf0** [comment]
@ysfjwd exactly what we need.

**Comment by Ardakilic** [comment]
@ctf0 Indeed, I'm not sublime text theme developer myself, but it was just an example how other people do it at least for sizes, which also was a part of the question.

Not ideal at all, but for now, if a setting cannot get parameter in theme, how about maybe some predefined fonts and font size combinations?

**Comment by ctf0** [comment]
@Ardakilic @ysfjwd 
- can you suggest like 3 or 4 font names to add to the settings.
- for the font-size i made settings for (12,13,14).

**Comment by ysfjwd** [comment]
Ubuntu Mono
Source Code Pro
Hack 
Consolas

These are the fonts i have seen being used amongst my pears.

**Comment by ctf0** [comment]
@ysfjwd perfect, will add them, can you aswell send me a copy of those fonts to include in the theme as not everyone have those installed on their machines.

**Comment by ysfjwd** [comment]
i don't know which OS you are on, but these are open source fonts, except consolas and i used homebrew to install. If you are not familiar with caskroom, here is how i go about it

```bash
brew install caskroom/cask/brew-cask
brew tap caskroom/fonts
brew cask install font-source-code-pro font-hack font-ubuntu
```

And consolas is by microsoft and the easiest way to get is to install visual studio code :smile:

**Comment by ctf0** [comment]
actually i meant putting all those fonts you want in one zipped package and send it over, and as i hate anything Microsoft i would rather get bitten by a stray dog than installing the visual studio. :metal:

**Comment by ysfjwd** [comment]
wouldn't it make your theme file a little like a couple of mbs ?

**Comment by ysfjwd** [comment]
okay hold that thought for a couple of hours .. let me upload the zip somewhere ..

**Comment by ysfjwd** [comment]
[2.5 mb file at dropbox :p](https://www.dropbox.com/s/ic0f8u5eppzrc14/code%20fonts.zip?dl=0)

**Comment by ctf0** [comment]
excellent, will see what i can do with it, thank :+1:

**Comment by ysfjwd** [comment]
oh wow ... thanks man!
