### ISSUE TITLE
Install of updates does not show message

### ISSUE THREAD

**Issue by fburleigh** [ctf0/Seti_ST3#117]
Seti_UI updates regularly -- good!  But for a long time now I never see update messages from Package Control.  I use the ST3 dev channel on current OS X and Windows, and PC is current on both.

**Comment by ctf0** [comment]
i encountered this along ago and i cant figure out the problem but anyway nothing changed with the theme structure it self ,so its related to the ST latest updates.

**Comment by fburleigh** [comment]
Thanks for your reply. Then perhaps I'll open an issue in Package Control.
