### ISSUE TITLE
Highlight modified tab colour

### ISSUE THREAD

**Issue by revolter** [ctf0/Seti_ST3#118]
It would be nice to be able to reset the highlight colour of the modified tabs to the default theme's orange and still use this theme if you have `highlight_modified_tabs` set to `true`.

**Comment by ctf0** [comment]
do u mean the blue underline ??

**Comment by revolter** [comment]
No. Using the default theme that comes with Sublime, if you set the `highlight_modified_tabs` to `true` in the user settings, any unsaved tabs will the their text colour set to orange.

**Comment by ctf0** [comment]
currently this option is already in the theme ,so i think what u r after is coloring the tab label it self ?

**Comment by revolter** [comment]
Right. Currently, using this theme, for modified tabs, the label's color is white, and I would like it to be orange or other color.

**Comment by ctf0** [comment]
i made it this way so the user don't get distracted by the too many colors ,also i believe the blue bar represent the idea perfectly without any other additions.

**Comment by revolter** [comment]
I see, but it would be nice at least to be able to explicitly change this behavior, while the default remains to the current one.

**Comment by ctf0** [comment]
i can make an option to color the tab label the same color as the tab blue bar.

**Comment by tomatau** [comment]
I like the coloured dot beside the tab as it currently is but I feel that having a modified tab is still quite an important piece of information -- so would prefer this to have the orange colour as it did in default sublime theme.

It wasn't too distracting before as it just encourages more frequent saves.

**Comment by ctf0** [comment]
@revolter send me the hex code of the color u want to use instead of the current blue.

**Comment by tomatau** [comment]
I believe the default is `#fd8801` or thereabouts

**Comment by ctf0** [comment]
added.
