### ISSUE TITLE
Toggle Comment not works with Gulpfile JS, SCSS, LESS

### ISSUE THREAD

**Issue by dacodekid** [ctf0/Seti_ST3#119]
**Toggle comment** - command (CMD + /) isn't working, at least for Gulpfile JS, SCSS & LESS, but does works selectively on few other formats (such as NPM JSON, Bower JSON).

**Comment by ctf0** [comment]
give me something to test with as currently i cant reproduce any of those.

**Comment by altrugon** [comment]
I ran into this problem too, and it's quite easy to replicate.

Open any *.scss file chose a line to comment (you don't need to highlighted it) and hit (CMD + /). This shortcut works on other files types like php, html, etc... but not with *.scss, *.less files.

Another related issue is the colour syntax of the comment, here is what's happening:

/* With this comment option I turned grey */

// With this comment option I don't change colour.

Thank you for this amazing theme.

**Comment by dacodekid** [comment]
@ctf0 , my apologize. Somehow I missed this notification.  After a very long I started using ST3 again just couple days back and still faced the same problem. But this time it was just the 'gulpfile'. Every other file extensions were working fine. Gave up and went back to Atom. After @altrugon 's comment here, I completely removed ST3 / reinstalled and the problem was gone. I tried several times to install/reinstall Seti UI & UX but this time it seems working fine.

**Comment by altrugon** [comment]
Thank you for your feedback dacodekid, I'll give it a try.

**Comment by dacodekid** [comment]
@altrugon :+1:

**Comment by ctf0** [comment]
u r facing issues because you need to have the main syntax languages for those you are having issues with then after that open any file you want to chose to always open it with the syntax you installed not with Sei_UI and it will work as expected.
