### ISSUE TITLE
less files syntax hilighting

### ISSUE THREAD

**Issue by teophilus** [ctf0/Seti_ST3#120]
- Needs improvement on the color scheme when nesting occurs
- '//' type comments are not accounted for, should appear like the /* */ comment

**Comment by ctf0** [comment]
should i even ask ???

**Comment by teophilus** [comment]
I found a work around so i'm sure others have too. Awesome job! I really like the theme.

**Comment by ctf0** [comment]
k great ,btw u may try the seti_ux as it have better support for the lang scopes.

**Comment by teophilus** [comment]
I tried it but i didn't like the color-scheme as much as the seti_ui: monokai.

**Comment by ctf0** [comment]
okey then ,maybe u can send me a PR so other can benefit or ur work around.

**Comment by teophilus** [comment]
it wasn't a crazy work around i just installed the less package. I will look into how the color schemes are generated and submit a PR when I can.
