### ISSUE TITLE
Seti_no_bar_undertabs behavior

### ISSUE THREAD

**Issue by adriano-di-giovanni** [ctf0/Seti_ST3#122]
Setting `Seti_no_bar_undertabs` to true, doesn't remove the colored bar under the tabs but only shifts the content area up. Is it the intended behavior?

Sublime Text 3, Build 3083, Mac OS X 10.10.2

**Comment by ctf0** [comment]
yeap ,it only removes the 4px bar under the tabs ,but the blue bar remains as this is the indicator of the modified tab.
