### ISSUE TITLE
Lighten folder labels

### ISSUE THREAD

**Issue by akloeber** [ctf0/Seti_ST3#124]
Would it be possible to make the folder labels in the sidebar lighter like in the original Seti UI?

Seti@ST3:
![bildschirmfoto 2015-04-13 um 17 14 09](https://cloud.githubusercontent.com/assets/968308/7118572/4e8c3022-e200-11e4-8362-ddd10d280935.png)

Seti@Atom:
![bildschirmfoto 2015-04-13 um 17 13 30](https://cloud.githubusercontent.com/assets/968308/7118575/5a01084c-e200-11e4-8c46-a6015eb2bca2.png)

**Comment by akloeber** [comment]
Adjusted colors from https://github.com/ctf0/Seti_ST3/pull/125:

![bildschirmfoto 2015-04-14 um 13 01 12](https://cloud.githubusercontent.com/assets/968308/7135582/798e3312-e2a8-11e4-89f0-aa7a5b3274f7.png)

**Comment by ctf0** [comment]
merged, thanx.

**Comment by akloeber** [comment]
@ctf0: in latest v9 the changes to folder label colors have been reverted.

**Comment by akloeber** [comment]
Using `Seti_orig` restores the old state.

**Comment by ctf0** [comment]
nothing has changed with the seti_orig, only the new theme have the changes.
