### ISSUE TITLE
Error loading syntaxt file "Packages/Seti_UI/Langs/license.tmLanguage": invalid include

### ISSUE THREAD

**Issue by zot24** [ctf0/Seti_ST3#127]
I'm seeing the following error:

![screen shot 2015-04-29 at 11 11 20](https://cloud.githubusercontent.com/assets/678498/7388839/832d9958-ee60-11e4-981b-0655b3cba0ad.png)

Just when I try to open the first time my `LiCENSE` file:

![screen shot 2015-04-29 at 11 12 54](https://cloud.githubusercontent.com/assets/678498/7388866/bfa98f04-ee60-11e4-9878-635c5ad6e740.png)

I track down the file `license.tmLanguage` to the path [Packages/Seti_UI/Langs/license.tmLanguage`](https://github.com/ctf0/Seti_ST3/blob/master/Langs/license.tmLanguage)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>LICENSE</string>
	<key>fileTypes</key>
	<array>
		<string>LICENSE</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string></string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>license</string>
</dict>
</plist>
```

I have to say I'm don't have a clue about what I'm doing but I removed this block:

```xml
<key>patterns</key>
<array>
	<dict>
		<key>include</key>
		<string></string>
	</dict>
</array>
```

And the error just gone! :smile:

I think that error is complaining about that empty `<string></string>` but not sure, could be that the problem? why I'm getting that error? and why I'm not receiving it any more?

**Comment by ctf0** [comment]
i have no logical explanation for that but check other lang files and u will know what each section means.

**Comment by zot24** [comment]
That is what I did and it seems like that bit is to check the file extension and because the LICENSE doesn't have an extension we got there that `<string></string>` empty but for X reason on my machine doesn't work :S

**Comment by ctf0** [comment]
send me something to test with and i'll see what i can do.

**Comment by zot24** [comment]
Could you just create a LICENSE file without extension and see if you get this error after close Sublime and open that file again, if it doesn't happens to you could be just an error on my environment like a collision with any other of my plugins, dunno.

Thanks @ctf0!

**Comment by ctf0** [comment]
after some testing i got the same error as u,and i just removed the pattern part as u mentioned b4,
i will push that update now ,thanx.

**Comment by zot24** [comment]
Thanks @ctf0 for you fast response! :smile:
