### ISSUE TITLE
Hard to see difference when many tabs are open.

### ISSUE THREAD

**Issue by tomatau** [ctf0/Seti_ST3#128]
If you have a lot of tabs open, they just get sort of mushed together.

Would be great if the thin black(?) line between each tab could be more visible, a light grey would be ideal so it isn't too distracting.

**Comment by ctf0** [comment]
send me a screenshot so i can re-produce

**Comment by tomatau** [comment]
![unclear-tabs](https://cloud.githubusercontent.com/assets/1243486/7452746/890fc81c-f259-11e4-9327-e10db0cafe94.jpg)

**Comment by ctf0** [comment]
i wish i could help u with this but currently i have no clue how to exactly do that :(

**Comment by tomatau** [comment]
np :)

**Comment by ctf0** [comment]
hello again, 
after going through a couple of themes i believe that ST doesn't currently support what you are after, so i will close this issue for now unless something changed later then i will surly update the theme with it :+1:
