### ISSUE TITLE
Highlight uncommited changed files in sidebar 

### ISSUE THREAD

**Issue by tomatau** [ctf0/Seti_ST3#129]
It's a minor detail and maybe not possible without further git integration for sublime text? Maybe there's a plugin that does this already for ST3 that I haven't found also..

But Atom SetiUI supports this out of the box and I think it's a very useful feature for at  glance tracking of your changes.

**Comment by ctf0** [comment]
it would be a good addition but unfortunately i don't use git with ST, i use another app just for that.

**Comment by sharkone** [comment]
[This](https://github.com/jisaacks/GitGutter) will do the trick!

**Comment by tomatau** [comment]
I'm already using git gutter - it solves a completely different problem regarding files that are already open....

I'm talking about indications in the __sidebar__

**Comment by sharkone** [comment]
Oh sorry nevermind then!

**Comment by ctf0** [comment]
this is more of a feature rather than an option to be added, so i will close this as its not related to the theme but more to the ST api.

**Comment by ctf0** [comment]
atm sublime only support this when using the `show opened files in sidebar` option
