### ISSUE TITLE
Sidebar display issue with latest update

### ISSUE THREAD

**Issue by mikeerickson** [ctf0/Seti_ST3#131]
The latest Seti_UI for ST3 was installed today and now nothing appears on the sidebar (all black)?  Is it possible to revert to previous version?

In fact, the whole UI is kinda messed up now.   Cant see list of options in popup windows (Command-Shift-P) 

I am on OSX

**Comment by oskargicast** [comment]
Same here. I am also using ST3 + ubuntu 14.04.

![selection_244](https://cloud.githubusercontent.com/assets/1572530/7615835/cf438d4c-f965-11e4-95e8-863352f65b05.png)

Thanks

**Comment by mikeerickson** [comment]
@oskargicast Did this just start happening after latest update?

**Comment by oskargicast** [comment]
Yes :(

**Comment by mikeerickson** [comment]
@oskargicast Not sure if it is ST update or Seti update, since both updated at same time.

**Comment by ctf0** [comment]
all i can say that it got nothing to do with the theme it self as the last update has only add a couple of options which doesnt effect the sidebar in anyway, try to restart ST and clear the cache.

**Comment by mikeerickson** [comment]
Well, I have done all the usual debugging tecniques and issue persisted.  

So, I restored previous version (from backup) and all worked!  I had to disable ST package "auto_upgrade" : false to prevent future seti updates, otherwise it will break again (repeatedly). 

There must be something in there causing it to break as EVERY time (I have reproduced several times) it updates to latest version

**Comment by ctf0** [comment]
on OSX & Win 7 all are good ,am using ST b.3083
