### ISSUE TITLE
Option to hide the sidebar icons?

### ISSUE THREAD

**Issue by simov** [ctf0/Seti_ST3#133]
I know it might sound crazy as this is one of the best features of this theme, but for some of my projects I found the file icons to be a bit distractive.

**Comment by ctf0** [comment]
which icon u want to hide ?

**Comment by simov** [comment]
The first option I'm thinking about is hiding all icons all together (just like it was in st2)

![no-icons](https://cloud.githubusercontent.com/assets/1694112/7792699/38ce2e90-02bf-11e5-887d-f19a62c382de.png)

Very minimalist, you can use the triangle for visual guidance which one is a folder or not (btw this screenshot is from st3 with the simple fix applied from [here](http://stackoverflow.com/a/25660634/1260020))

The other option that I was thinking about was hiding only the file type icons, but right now I don't think that would be necessary (I'm changing the title of the issue)

**Comment by ctf0** [comment]
both options added.

**Comment by simov** [comment]
Just tried it. Nice! :)
