### ISSUE TITLE
Seti_sb_tree_miny - bigger file indentation

### ISSUE THREAD

**Issue by simov** [ctf0/Seti_ST3#134]
I'm using the `"Seti_sb_tree_miny": true,` option which is great for my needs, but I think the inner folder items need a little bit more padding to the left:

![item-indentation](https://cloud.githubusercontent.com/assets/1694112/7787699/7e6f1b14-0222-11e5-99ca-70852aa0ea19.png)

It's really hard to distinguish which files are located in the `flow` folder, and which are located directly in the `lib` folder.

**Comment by ctf0** [comment]
actually it was what u r after b4 but the use that asked for this option was happy with the current settings, i will try to implement what u r after in a separate option.

**Comment by simov** [comment]
That would be great! I'm posting again the same screenshot from my other issue

![no-icons](https://cloud.githubusercontent.com/assets/1694112/7792807/02f5f478-02c0-11e5-8560-7d0082522149.png)

As you can see there are just a few more pixels to the left, but just to enough to easily distinguish the nesting levels.

**Comment by ctf0** [comment]
changed.

**Comment by simov** [comment]
Thanks! I saw that :+1:
