### ISSUE TITLE
Sidebar display bug

### ISSUE THREAD

**Issue by Charleelee** [ctf0/Seti_ST3#135]
I was working on a project when suddenly my sidebar switched from normal seti ui color scheme with icons to a grey white ish color with no icons.

![seti_bug](https://cloud.githubusercontent.com/assets/8321562/7799876/1ae332de-02da-11e5-8bf8-f4a29ad41261.png)

**Comment by ctf0** [comment]
you need to just restart the app as the current theme is the default not seti.

**Comment by Charleelee** [comment]
Yeah somehow it reverted to default by itself, I putted it back to seti but now everything is broken... even in default. My guess is that something got corrupted, im gonna do a fresh install.
![sublime_seti_broken](https://cloud.githubusercontent.com/assets/8321562/7802190/d75a5a9a-02fe-11e5-8556-468f40305650.png)

**Comment by ctf0** [comment]
i will close this for now, if something came up i'll re-open it

**Comment by raptor235** [comment]
I had the same thing happen last night... installed jshint gutter plugin and all of a sudden the entire theme is dead... the tabs are regular sidebar is same as default... the colors in the main window seem to work ok just everything out of the main window seems broken... any ideas?

**Comment by ctf0** [comment]
have no idea ,and am also using the same plugin on OSX and everything is good.

**Comment by ctf0** [comment]
@raptor235 have no idea ,and am also using the same plugin on OSX and everything is good.
