### ISSUE TITLE
Display a different icon folder for symbolic links in the sidebar

### ISSUE THREAD

**Issue by Devnco** [ctf0/Seti_ST3#137]
Hello, first thanks for your work, great theme !

As mentioned in the title, I think it could be a nice improvement for many projets which used symbolic links to display a different icon than classic folder. I don't know if it's possible cause I haven't found any theme which have this feature yet.

Thanks and regards,
Jeremy Jamar

**Comment by ctf0** [comment]
if u can have this with the default theme, then take a screenshot and send it over as currently i don't know what exactly r u after.

**Comment by Devnco** [comment]
As I told, I didn't find this feature on any sublime theme yet, but here is a screenshot on Atom with these icons : A folder/file for real folder/file and a arrowed folder/file icon for simlinks (ln -s)

![screen shot on 2015-05-27 at 16-11-50](https://cloud.githubusercontent.com/assets/2128842/7838135/830b5334-048b-11e5-8708-7363a34a9394.png)

**Comment by ctf0** [comment]
then i believe u should request this as a feature to be added to ST, as i don't know how to implement this into the api.
