### ISSUE TITLE
Latest update seems to break ui

### ISSUE THREAD

**Issue by newswim** [ctf0/Seti_ST3#139]
I got an alert that the build had updated this morning, now the regular sublime skin remains even after i alter user config.

**Comment by ctf0** [comment]
mmmm, some users have seems to have things like this and all i can say thats its an individual cases as mostly everything should work without any probs.

**Comment by newswim** [comment]
Fixed it, the "theme" field was getting overwritten

**Comment by ctf0** [comment]
great :+1:
