### ISSUE TITLE
user preferences > color sheme and theme bug

### ISSUE THREAD

**Issue by dhenriet** [ctf0/Seti_ST3#141]
I need to insert user preferences everedy day to active seti UI theme, 

```
{
  "theme": "Seti.sublime-theme",
  "color_scheme": "Packages/Seti_UI/Scheme/Seti.tmTheme",
}
```
before I didn't have this problem. I am on  windows 7 with  sublime texte 3 build 3083

![screenshot_1](https://cloud.githubusercontent.com/assets/4640027/8001751/f36e0ec6-0b68-11e5-88ea-0f7d2268bf0d.png)

**Comment by ctf0** [comment]
i have the same setup and i dont need to do the above, 
1- try to clear the cache folder.
2- try to remove everything but the theme and see if it works.
