### ISSUE TITLE
Hard to see the line highlight

### ISSUE THREAD

**Issue by mucsi96** [ctf0/Seti_ST3#142]
For me sometimes it's very hard to see the line highlight
![Seti Screenshot](https://raw.githubusercontent.com/ctf0/Seti_ST3/master/%2Bres/screenshot-1.png)

I think this would be much more better: 

     <key>lineHighlight</key><string>#2a363c</string>

![Idea](https://lh3.googleusercontent.com/U7WXCjs3WZln37xk0cGCs68jhzvoZFwn6EEgVr6-LUa2TaC2Z9_hyuf9NPP45JM83I-i83-JwxGRwEQ=w1896-h847-rw)

**Comment by ctf0** [comment]
will see what i can do.

**Comment by ctf0** [comment]
an easier solution would be copying the scheme file to **Packages/Theme - Default** and change anything u want, this way ur settings wont be lost on file updated.

**Comment by mucsi96** [comment]
Thanks!

**Comment by revolter** [comment]
Can't there be a customizable setting for this one?

**Comment by ctf0** [comment]
@revolter can u show me a ss ?
