### ISSUE TITLE
Markdown highlighting missing

### ISSUE THREAD

**Issue by kgizdov** [ctf0/Seti_ST3#144]
Hi,

Thanks for a great color scheme.

I'll just reference this here #100 to get it out of the way. Even though this issue is closed, I can barely see any markdown highlighting in Seti_UI or Seti_UX.

Now I don't want my post to be a rant, because I really like Seti_UI and I appreciate the work put into it, but I have come to the point where I have to dynamically switch color schemes when editing markdown. To give an example of what I mean, here's a shot of what I see in Seti_UI, Seti_UX and what I switch to:

![Seti_vs_UX_vs_Dayle_Rees_Fr_Con](http://i.imgur.com/xlwIv6F.png)

Regards.

**Comment by ctf0** [comment]
thanx for the heads-up, currently what i want from u is
1- send that file in the ss to test with.
2- send me the name of the color scheme file that u usually use.

**Comment by kgizdov** [comment]
here's a paste of the file - http://pastebin.com/mikJKNh0

the color scheme is part of Dayle Rees Color Schemes, in particular - Frontier Contrast

I've used Markdown Extended before, but it's a bit too much for me. I prefer the simple highlighting option. I've seen these other one, HTML5 is indeed really good, but for CSS3 I prefer hayaku - it's really really fast and easy to use. Thanks for the suggestions anyway!

**Comment by kgizdov** [comment]
Just updated the file with a more complete syntax examples - still on the same link

**Comment by ctf0** [comment]
updated, check now.

**Comment by kgizdov** [comment]
not sure if I did something wrong, but I get this:

![error](http://i.imgur.com/ZeE9llo.png)

**Comment by ctf0** [comment]
i dont know the reason but the file is working fine over here on windows, also it still need more works after u updated the file, so i will look into that later.

**Comment by kgizdov** [comment]
Maybe, I'm doing it wrong. Could you then update the Package repo, so Sublime updates it automatically?

**Comment by ctf0** [comment]
i already did that.

**Comment by kgizdov** [comment]
still showing as updated 3 months ago on 19/03/2015

**Comment by ctf0** [comment]
it takes an hour to show up on PC.

**Comment by kgizdov** [comment]
Had to install Markdown extended to make some of it work but here are a few more that are missing. Especially, lists are not behaving https://goo.gl/photos/5DaSY3oyP31xMxhbA

**Comment by ctf0** [comment]
does those other things gets HL in other schemes or do u have the same result no matter the scheme u use ?

**Comment by ctf0** [comment]
i updated the scheme, also here is a better formatted file or ur md
https://gist.github.com/49308186b2de385ad9f5.git
