### ISSUE TITLE
Background of tab bar is yellow since v9

### ISSUE THREAD

**Issue by akloeber** [ctf0/Seti_ST3#145]
Since latest v9 the background of the tab is yellow:
![bildschirmfoto 2015-06-13 um 10 52 06](https://cloud.githubusercontent.com/assets/968308/8143712/486bd00a-11ba-11e5-9e75-ed1a30457831.png)

Was that an intentional change?

**Comment by Henridv** [comment]
![seti_pink](https://cloud.githubusercontent.com/assets/467201/8143727/0e6860ac-11bb-11e5-8cd0-0e22b88730c3.png)

With me it's pink and blue.
But it seems to be OK if I use Seti_orig instead

**Comment by akloeber** [comment]
Now that's funny : -)

**Comment by akloeber** [comment]
I can confirm that using `Seti_orig` fixes this behavior.

**Comment by ctf0** [comment]
that is intentional because now depends on the scheme hue "light,black,med" the tab colors will change.

**Comment by akloeber** [comment]
Is this a property configured int the color scheme? I'm not using the Seti color theme but Monokai Bright instead.

**Comment by ctf0** [comment]
i dont know how exactly st measure the contrast of the scheme, but use something like **schemer** and u will get to see the "light,black,med" next to each scheme u have on ur machine.

**Comment by simov** [comment]
![sublime-tabs](https://cloud.githubusercontent.com/assets/1694112/8144337/60b2171e-11e2-11e5-8c1f-13eb59fc27f8.png)

@ctf0 how exactly can I change the tabs scheme back to the square ones? I tried changing the color scheme to Seti_orig but it's the same, also I'm using customized Monokai theme.

**Comment by whitefoxy** [comment]
Wonderfull! The theme is completly broken, new ... tabs and color scheme looks like in standart sublime theme.

![preferences sublime-settings 2015-06-14 12-39-59](https://cloud.githubusercontent.com/assets/6276815/8148076/9aa2375a-1292-11e5-965c-cee5fa2d78b8.png)

**Comment by skechboy** [comment]
I'm experiencing the same problem, switching to Seti_monokai solved the color problem, the problem with the squares tabs can be solved by changing to the original theme as @simov said:

```"theme": "Seti_orig.sublime-theme```

**Comment by ctf0** [comment]
@whitefoxy & @skechboy am sorry for the inconvenience but i've already stated the changes i made in the update read me so everything should be just fine as u just need to change the theme from `Seti` to `Seti_orig` and thats it

**Comment by ctf0** [comment]
i think this has been solved, so if any have a better idea for the tab colors instead of the current plz make a PR.

**Comment by julienpa** [comment]
Ok for the tabs with Seti_orig theme, but what about the color_scheme for the code? It is back to default ST colors and I can't seem to find how to get Seti colors back for me code...
![st_seti](https://cloud.githubusercontent.com/assets/4720300/8165267/4cddce82-138f-11e5-887d-7116f09ef771.png)  
I tried with both:
```
	"color_scheme": "Packages/Seti_UI/Scheme/Seti_orig.tmTheme",
	"theme": "Seti.sublime-theme",
```
and
```
	"color_scheme": "Packages/Seti_UI/Scheme/Seti_orig.tmTheme",
	"theme": "Seti_orig.sublime-theme",
```
Any hint on that? Thanks!

**Comment by montchr** [comment]
I'm not sure that this issue is solved. Just updated theme this morning. Still happening for me. If it's still happening for some people, and the only solution is to revert to Seti_orig, then there's still a problem.

> i think this has been solved, so if any have a better idea for the tab colors instead of the current plz make a PR.

The color should be whatever it was before.

**Comment by ctf0** [comment]
@montchr all of that was already stated in the latest update read me.

**Comment by ctf0** [comment]
next update the current behavior for the tab will be removed and all schemes will use the same tab look.
