### ISSUE TITLE
PHP Icon

### ISSUE THREAD

**Issue by Private-Storm** [ctf0/Seti_ST3#149]
Well for whatever reason I've lost the PHP file icon in my sidebar instead default icon is shown. Other then that any other file type display's the correct file icon.

**ST 3092 (dev channel)**
I have checked (Packages/Seti UI/Prefs/icon_php.tmPreferences) which seems correct to me.

*User Pref:* 

"color_scheme": "Packages/Seti_UX/Seti.tmTheme,
"theme": "Seti_orig.sublime-theme"

**have you restarted ST after you installed the theme ?.**
Yes

**if you still have bad render ,have you removed the cache folder ? (found right next to the packages folder).**
Yes

**have you copied the files from the "Ext" folder to your User folder ?.**
Yes

![shot](https://cloud.githubusercontent.com/assets/1253735/8147714/22d9244e-127a-11e5-877b-9c0255d1aeee.png)

**Comment by ctf0** [comment]
actually u r missing more than just php icon, i believe this is related to the st version, am still using the stable channel release, try it and see if u still have the problem.

**Comment by Private-Storm** [comment]
Well not sure whats else I've been missing I'll noticed php only at the moment. But I could try if you let me know which file_type should have the default icon only.

**Comment by gerardroche** [comment]
>= 3092 uses the new syntax system. The PHP syntax root scope has changed and is not loaded via the HTML syntax anymore e.g. see https://github.com/gerardroche/sublime-php-grammar/blob/master/CHANGELOG.md#090

Change the `Prefs/icon_php.tmPreferences` scope to `embedding.php`. 

Or try the `seti` branch of https://github.com/gerardroche/sublime-php-grammar

**Comment by gerardroche** [comment]
Can and should syntax packages provide an icon preferences configuration?

**Comment by Private-Storm** [comment]
That did the trick for PHP thank you!

**Comment by ctf0** [comment]
@gerardroche big thanx for ur hard work, i will definitely support this once the new build becomes the standard.
