### ISSUE TITLE
Tab-Style back to default.

### ISSUE THREAD

**Issue by tournier** [ctf0/Seti_ST3#150]
Seti_UI's tab style is being overwritten by the Sublime Default tab style, wich is kind of ugly...

![capture](https://cloud.githubusercontent.com/assets/6617571/8148943/456515ca-12b3-11e5-809b-f40ed9f3bfca.PNG)

Tried to reinstall Seti_UI, still the same.
I haven't change anything, there's been a small updates this morning when i started ST3 and now it's like that.

**Comment by AntoineBoulanger** [comment]
+1

**Comment by joselmilla** [comment]
+1

**Comment by ctf0** [comment]
https://github.com/ctf0/Seti_ST3/issues/145
https://github.com/ctf0/Seti_ST3/blob/master/messages/9.txt

**Comment by treong** [comment]
I also get this weird color on the tab bar after updated, does anyone know how to reset to the old version?
![image](https://cloud.githubusercontent.com/assets/4222249/8151488/56acddac-1341-11e5-9875-f63753c914bd.png)

**Comment by yinone** [comment]
so ugly! I can't stand the default style!
