### ISSUE TITLE
Yellow Tabbar

### ISSUE THREAD

**Issue by jbennecker** [ctf0/Seti_ST3#151]
since the update yesterday i get a yellow tabbar

![screen shot 2015-06-15 at 09 33 08](https://cloud.githubusercontent.com/assets/2862964/8155157/9b0122ec-1341-11e5-91e2-fba08d5ee291.png)

**Comment by bhappyz** [comment]
Same issue here, the tabs are not being styled properly even with no yellow bar

**Comment by bhappyz** [comment]
Ok here is the solution 

https://github.com/ctf0/Seti_ST3/blob/master/messages/9.txt

you need to change the theme to this in your settings (its Seti_orig instead of Seti)
"theme": "Seti_orig.sublime-theme",

**Comment by jbennecker** [comment]
aaahhh :)

**Comment by nuragic** [comment]
Thanks so much @bhappyz, I almost crack up with this *$@#¢“”!
