### ISSUE TITLE
Can you add spacing and contrast to the command pallete? 

### ISSUE THREAD

**Issue by iamdarrenhall** [ctf0/Seti_ST3#152]
There's not much contrast between the command pallete and the main window, could the background colour of the command pallete be lighter? And also, could there be more spacing on the search input field? Feels a bit tight to me :–D

![screen shot 2015-06-15 at 10 46 08](https://cloud.githubusercontent.com/assets/2150098/8157409/832941e4-134c-11e5-9e2b-e59bb3815e4e.png)

**Comment by ctf0** [comment]
the pallete bg color is the same as the original port but yes am thinking of changing it as currently its kinda distractive, and for the space yeah u r right it needs more space, i'll see what i can do.

in the meanwhile if u have a suggestion for the panel colors plz tell me.

**Comment by julienpa** [comment]
Maybe something a bit lighter, or at least with a border around to mark the difference with the coding area? Since you type your commands in a box without borders and with the exact same color as the coding area, it's very confusing and I always think that I am actually editing my file instead of typing a command.

Thanks!

**Comment by iamdarrenhall** [comment]
OK, so I've mocked something up, couldn't get the right font but you can see what I mean. Might be a good idea to unify the colours with the find and replace panel or any additional UI elements that come in to the main window.  Can provide the PSD I used here if anyone else wants to have a go.

Disclaimer: I'm not a designer!

![idea](https://cloud.githubusercontent.com/assets/2150098/8180466/f8ed81fa-1415-11e5-9943-c6fefcbe8fb2.jpg)

**Comment by julienpa** [comment]
That's very nice @iamdarrenhall! Congrats, it'd be glad to have it in my editor :)

**Comment by ctf0** [comment]
@iamdarrenhall for the coloring its done + changed the brown color for something more subtle, for the spacing i'll try it later as i cant remember what to change atm.

**Comment by ctf0** [comment]
**update:**

more spacing will be added to the quick panel in the new update, 
if you want to have a different color for the `search panel` other than the `quick panel`, plz give me the hex code for it & i will add it in a separate setting.
