### ISSUE TITLE
Update Has Caused Graphical Issues

### ISSUE THREAD

**Issue by mdavis1982** [ctf0/Seti_ST3#154]
The update a day ago has caused my tab bar to look like this:

![screen shot 2015-06-15 at 12 36 51](https://cloud.githubusercontent.com/assets/199807/8159099/83b21190-135b-11e5-9375-52c9e9005fe1.JPG)

Nothing I do fixes it, apart from changing the theme to something different.

I've removed the cache folder and done everything else suggested but I'm still getting this problem.

**Comment by yavorski** [comment]
+1. Same problem here.

**Comment by ewistrand** [comment]
+1 Also having the same issue

**Comment by sabarasaba** [comment]
I got the same thing, tried removing it and adding it back but didn't do anything.

**Comment by montchr** [comment]
Same issue here as well.

Temporary workaround: switch to the theme `Seti_orig`.

**Comment by michaeljpowell** [comment]
+1 same issue here

**Comment by YesImAaron** [comment]
Also having the same issue

**Comment by chryton** [comment]
+1 same issue here. Workaround seems to work fine.

**Comment by ctf0** [comment]
https://github.com/ctf0/Seti_ST3/issues/150
