### ISSUE TITLE
Bring the old square tabs back ? Question?

### ISSUE THREAD

**Issue by yavorski** [ctf0/Seti_ST3#155]
Hi, today my Seti theme updated and I noticed we have these new tabs. Although they looks good, could we have an option for bringing back the square tabs? I am attaching a screenshot. Thanks in advance.

![tabs-seti](https://cloud.githubusercontent.com/assets/3436517/8159196/fab0a642-136c-11e5-9be9-fa5593287d2f.jpg)

**Comment by martinAnsty** [comment]
I'm reasonably sure something has gone wrong in the most recent release. These rounded tabs look a lot more like the default Sublime tab style than the Seti style tabs. There have also been a number of other issues raised (see #154)

**Comment by martinAnsty** [comment]
Well I was completely wrong, this change was seemingly on purpose. There are now two themes included in the plugin: SETI and SETI_orig. For the square tabs you want to choose SETI_orig

**Comment by yavorski** [comment]
Thank you for your answer, and your work. The theme is awesome!
This fixed the issue: 

```"theme": "Seti_orig.sublime-theme",```

**Comment by justrhysism** [comment]
Original SETI FTW!

**Comment by btm1** [comment]
dude absolutely original is def FTW dump that lame tabs that look like the default
