### ISSUE TITLE
New tabs and different color schemes.

### ISSUE THREAD

**Issue by brunolazzaro** [ctf0/Seti_ST3#157]
I use the original tabs, but I've noticed that when using a different theme than the ones that come with Seti the tab bar can have some unexpected coloring. For example, here is how it looks when using Cobalt2:

![captura de pantalla 2015-06-15 a las 12 27 41](https://cloud.githubusercontent.com/assets/689386/8163607/7dcd970a-135a-11e5-9d98-0f14c42f00f1.png)

**Comment by ctf0** [comment]
https://github.com/ctf0/Seti_ST3/issues/145

**Comment by brunolazzaro** [comment]
Ooops, sorry! :disappointed:
