### ISSUE TITLE
Any light color scheme recommended?

### ISSUE THREAD

**Issue by cachitas** [ctf0/Seti_ST3#159]
I tried the Sublime default ones but none seemed to work.
Is there a light color scheme supported that you know of?
Currently I use Tomorrow Night: the dark variants work fine but the Blues and the lighter (default) do not.

**Comment by ctf0** [comment]
i cant think of any in particular now but one of the schmes i like is wild-cherry https://packagecontrol.io/packages/Wild%20Cherry

**Comment by cachitas** [comment]
I am not asking for a color scheme to use, I'm saying that some of them with this theme (Seti) may not be working properly. For instance, I tried the theme you mentioned (wild cherry) and it shows a yellow bar behind the names of the files I have open. This yellow (sometimes pink) bar looks completely out of the color scheme. This happens with some color schemes I have tried. As I mentioned, Tomorrow-Night Bright seems to work properly, but I would like to also have a working light theme alternative.

**Comment by ctf0** [comment]
ah am sorry for that ,currently i dont have a solution for that ,also check https://github.com/ctf0/Seti_ST3/issues/156

**Comment by cachitas** [comment]
Switching to the theme Seti_orig fixes it. Looks like it is just a matter of changing the background color of the tabs area with the modified tabs of Seti theme. I have no idea if this is possible.

**Comment by ctf0** [comment]
unfortunately its not because u will have to modify the theme file it self.

**Comment by ctf0** [comment]
@cachitas by the time i made the theme i wanted to make all the options available to the user, however in the next release i have removed that and all the schemes no matter what color tint it use the tab area will remain the same.
