### ISSUE TITLE
Script tags syntax coloring

### ISSUE THREAD

**Issue by peduxe** [ctf0/Seti_ST3#160]
The coloring doesn't seem to match <script> tags.

**Comment by peduxe** [comment]
http://i.imgur.com/ggoirkb.png

**Comment by peduxe** [comment]
http://i.imgur.com/ggoirkb.png

**Comment by ctf0** [comment]
what coloring ?

**Comment by ctf0** [comment]
i'll see what i can do

**Comment by ctf0** [comment]
@peduxe which scheme are u having this problem with ?

**Comment by peduxe** [comment]
@ctf0 Seti-ui original.

**Comment by ctf0** [comment]
@peduxe am sorry for the long delay but currently am super busy with other things and this scheme needs a lot of work so you can either make the changes you want and send me e PR or use Seti_UX instead.
