### ISSUE TITLE
My tabs don't look like the picture listed on the site

### ISSUE THREAD

**Issue by btm1** [ctf0/Seti_ST3#161]
https://packagecontrol.io/packages/Seti_UI

My tabs don't look like this and I've followed all the steps installing via package control

I've also dumped my cache folder. What am I doing wrong?

![screen shot 2015-06-18 at 11 21 34 am](https://cloud.githubusercontent.com/assets/4110944/8238702/39241dbe-15ac-11e5-86f0-67abfd7ed434.png)

**Comment by joseazr1987** [comment]
I think this can help you https://github.com/ctf0/Seti_ST3/issues/155

**Comment by btm1** [comment]
yep that's did it ... the old tabs look way way better

**Comment by ctf0** [comment]
https://github.com/ctf0/Seti_ST3/issues/156
