### ISSUE TITLE
Request: Better json syntax highlighting

### ISSUE THREAD

**Issue by TheDutchCoder** [ctf0/Seti_ST3#162]
Not sure if this is possible in ST,  but JSON files are very hard to read because practically everything is blue right now.

Is it at all possible to make a distinction between keys and values?
If so, "blue": "yellow" would be great, with white for commas, colons, etc.

Let me know if this is something I can do myself and submit a PR for.

**Comment by ctf0** [comment]
yes plz go for it and send me the PR or use seti_ux instead.
