### ISSUE TITLE
Blue tab bar disappeared

### ISSUE THREAD

**Issue by oxxostudio** [ctf0/Seti_ST3#163]
My blue tab bar disappeared suddenly, 
I tried to reinstall the sublime but can't solve, 
How can I solve this problem? :)
screenshot: https://goo.gl/fyWSH4

**Comment by NumEricR** [comment]
You should use the "Seti_orig" theme:
```"theme": "Seti_orig.sublime-theme"```

And then restart SublimeText

See #156 and #145.

**Comment by oxxostudio** [comment]
It's ok and It seems good, thank you very much :)
