### ISSUE TITLE
Tabs are not rectangle

### ISSUE THREAD

**Issue by phoenixwizard** [ctf0/Seti_ST3#164]
In the readme I see that the tabs transform to square/rectangle, while in my system the tab structure remains like the default theme. The screenshot below should be able to help. Not sure if I am missing a setting of not. My Sublime Preference : 

```
	"theme": "Seti.sublime-theme",
	"color_scheme": "Packages/Seti_UI/Scheme/Seti.tmTheme",
	"file_exclude_patterns":
	[
		".DS_Store",
		"._*"
	],
	"folder_exclude_patterns":
	[
		".svn",
		".git",
		".sass-cache",
		".log"
	],
	"ignored_packages":
	[
		"Vintage"
	],
	"trim_trailing_white_space_on_save": true
```

![screenshot 2015-06-23 15 14 26](https://cloud.githubusercontent.com/assets/289660/8303301/9d31ce98-19ba-11e5-9a22-d300ccc68ddf.png)

**Comment by NumEricR** [comment]
You should use the "Seti_orig" theme:
```"theme": "Seti_orig.sublime-theme"```

And then restart SublimeText

See #156 and #145.

**Comment by phoenixwizard** [comment]
@NumEricR : Thanks a lot. Worked like a charm !! Shouldn't this be added to the readme as well?

**Comment by ctf0** [comment]
@NumEricR  thanx
