### ISSUE TITLE
Documentation on changing/settings Icons for file type

### ISSUE THREAD

**Issue by ginfuru** [ctf0/Seti_ST3#165]
I'm not sure if this is even possible but From your screenshot in the README you've got PHP and HTML   working, but for some reason my PHP and HTML are the gear icon, _see below_. 

![screenshot](http://d.pr/i/9J2I+)

**Comment by joseazr1987** [comment]
Hi @ginfuru,
Have you tried to reinstall the theme again?

**Comment by ginfuru** [comment]
@joseazr1987 I have... with no luck. I'm currently using **ST3 Dev Channel Build 3092**

**Comment by joseazr1987** [comment]
I'm using the **ST3 Stable Channel, build 3083** and I don't have any issue, maybe changed something unexpected on that build, so that's a good point to start.

**Comment by ctf0** [comment]
@joseazr1987  plz use the stable build.
