### ISSUE TITLE
Maintain original tabs after update

### ISSUE THREAD

**Issue by giancarlorosa** [ctf0/Seti_ST3#171]
Hi. After update Seti_Ui changes the tab style. There is a way to Maintain it, because the original style is more better. Thanks!

**Comment by joseazr1987** [comment]
Hi @giancarlorosa, Have you tried this theme?
```json
    "color_scheme": "Packages/Seti_UI/Scheme/Seti_orig.tmTheme"
```

**Comment by ctf0** [comment]
plz check other issues b4 creating a new one https://github.com/ctf0/Seti_ST3/issues/156
