### ISSUE TITLE
Seti Tabs not displaying since last sublime update

### ISSUE THREAD

**Issue by finnbuster** [ctf0/Seti_ST3#172]
With Sublime build 3083 the default Sublime tabs are showing instead of seti tabs
![screen shot 2015-07-01 at 2 20 56 pm](https://cloud.githubusercontent.com/assets/2063384/8447528/a79231f4-1ffd-11e5-99be-e5a7cd130c85.png)

**Comment by vassyz** [comment]
I've got this issue as well, and "highlight_modified_tabs" doesn't seem to work. I'll have to switch to another theme until this gets fixed, because it makes find and replace all quite difficult to manage.

**Comment by ctf0** [comment]
why ppl don't check other issues b4 making a new one ????
https://github.com/ctf0/Seti_ST3/issues/156

**Comment by NumEricR** [comment]
@ctf0 Maybe you should add a note in your README.md because "Seti_orig" isn't mentionned ;)

**Comment by ctf0** [comment]
@NumEricR i was thinkin about that for a while, i will update that asap.
