### ISSUE TITLE
Yellow color at the top when removed Colo Scheme

### ISSUE THREAD

**Issue by kamaroly** [ctf0/Seti_ST3#173]
When I remove Seti color scheme, I am getting yellow at the tabs, can you help me to avoid this yellow color ?

![screen shot 2015-07-01 at 9 22 22 am](https://cloud.githubusercontent.com/assets/3633772/8449559/c39e1a0a-1fd2-11e5-9bed-0821f308db20.png)

**Comment by ctf0** [comment]
plz check other issues b4 making a new one
https://github.com/ctf0/Seti_ST3/issues/145

**Comment by kamaroly** [comment]
@ctf0 thanks
