### ISSUE TITLE
Theme makes some dialogs hard to read

### ISSUE THREAD

**Issue by kgizdov** [ctf0/Seti_ST3#174]
Hi,

I noticed it first when I opened the update dialog the other day:

![update dialog](http://i.imgur.com/eb2Tb3Z.png)

As you can see you can see, it is very hard to make out the writing. However, this doesn't seem to occur in the about dialog for whatever reason:

![update dialog](http://i.imgur.com/HOhW1mP.png)

**Comment by ctf0** [comment]
this been discussed b4, as unfortunately currently ST treats all the dialogue of the app the same, so this dialogue is unreadable because the font color is white which if i changed u wont be able to read the text in the console.
