### ISSUE TITLE
Make the horizontal scrollbar fixed

### ISSUE THREAD

**Issue by DannyFeliz** [ctf0/Seti_ST3#175]
I really love this theme, but there is just one thing that i would like to change, just to make the horizontal scrollbar fixed because if you are not over the scrollbar is invisible, I would like to make it always visible.

**Comment by ctf0** [comment]
this is related to the user settings not the theme ,  "overlay_scroll_bars": "system" or "disabled" which will effect all the scrollbars not only the horizontal.

**Comment by DannyFeliz** [comment]
Ohh that's right. Thank you.
