### ISSUE TITLE
Solid tabs and underbar not showing

### ISSUE THREAD

**Issue by sudostack** [ctf0/Seti_ST3#179]
ST3 3083. I've restarted after installing the theme.

After the latest update, my tabs are not showing any highlights, no underbar, and are not solid anymore. Any ideas, gentlemen?

**Comment by joseazr1987** [comment]
Did you had any Seti configuration option in your sublime preferences preferences?

**Comment by sudostack** [comment]
@joseazr1987 yeah...

`"theme": "Seti.sublime-theme"`
and
`"Seti_sb_tree_tiny": true`

The only settings listed in the README are for removal of the underbar and other tab settings, but I'm assuming the theme will, by default, apply the square tabs and underbars...?

**Comment by joseazr1987** [comment]
There are two themes one with tabs with rounded corners , and other with the square tabs.

Use this configuration option
``` 
"theme": "Seti_orig.sublime-theme"
```
See #153 

Regards.

**Comment by sudostack** [comment]
@joseazr1987 thanks for that! :+1:
