### ISSUE TITLE
Dog (pug) image with split pane view

### ISSUE THREAD

**Issue by sudostack** [ctf0/Seti_ST3#181]
<img width="1440" alt="screenshot 2015-08-12 14 03 13" src="https://cloud.githubusercontent.com/assets/861147/9236684/0e512972-40fb-11e5-98bb-42bb98a463e3.png">

Okay, I don't remember when, but some months ago when the Seti was updated, I would open ST3 with split pane (vertical), one to my left and one to the right WITHOUT any tabs/files open and I would see a pink background image with a dog on it. It's a pug to be more specific. Can we please allow this to be disabled?

**Comment by ctf0** [comment]
yes sure ,you can simply remove the `empty.png` from `main/xyz`

**Comment by sudostack** [comment]
@ctf0 thanks! Had no idea this was the setting that activated/deactivated it.

**Comment by ctf0** [comment]
thats why it was named "in_4_a_treat" LOL

**Comment by sudostack** [comment]
@ctf0 lol
