### ISSUE TITLE
Square tabs?

### ISSUE THREAD

**Issue by patrickbjohnson** [ctf0/Seti_ST3#183]
I've heard the Seti original had square tabs and sublime-based tabs as an option but doesn't seem to be the case in Seti for SB3. Is there an undocumented option to change this back to square tabs?

**Comment by ctf0** [comment]
actually you just need to activate `Seti_orig.sublime-theme` for the square tabs or if you prefer the original look for the tabs then activate `Seti.sublime-theme`
