### ISSUE TITLE
Freezing up my computer on startup

### ISSUE THREAD

**Issue by eorroe** [ctf0/Seti_ST3#184]
So for a while now, whenever I startup sublime text, it freezes up my whole computer.

To check if it was Seti_UI doing this, I disabled the package, and restarted sublime text (which it ran smoothly)

I enabled back the package and restarted Sublime Text and it froze again.

So I'm assuming their something that Seti_UI is running on startup that's causing sublime text to freeze up my computer.

Not sure how to inspect sublime text, so please let me know how I can help debug this problem.

Thanks.

**Comment by ctf0** [comment]
am still using the stable build which is 3083, if you are using the dev builds, am sorry there aint much i can do, but i will leave this open for future reference.

**Comment by eorroe** [comment]
Well what I mentioned above about disabling, and enabling was true, but I've disabled Seti_UI and closed sublime for a while and reopened and it froze too, but not as long as with Seti_UI enabled.

So it seems that the only reason Seti_UI would make it freeze longer because its just an extra step that Sublime has to do.

I'm really not sure what it is, and I'm using the stable version 3083 too, so I guess its not Seti_UI's fault sorry for the inconvenience

**Comment by ctf0** [comment]
sure no problem, but what i would recommend is to check the packages you started to have the freezing after, also use the console to see what packages get loaded and what get ignored + what errors show up.

**Comment by eorroe** [comment]
Sure did, I forgot I actually downloaded another package, which I didn't even use: [FuzzyFilePath](https://packagecontrol.io/packages/FuzzyFilePath) well as of right now its not freezing up like it used to, with Seti_UI enabled, so it may be that package, but I'll give it a couple days if it doesn't freeze up, I'll download it again and tests, and then you know file an issue on them.

BTW if by any chance you're using that package, mind telling me how to set it up (That's why I never used it) I don't know how to setup the settings.

Thanks, again sorry for the inconvenience wrong package.

**Comment by ctf0** [comment]
actually instead of FFP i would recommend
https://packagecontrol.io/packages/Open-Include
&
https://packagecontrol.io/packages/AutoFileName

**Comment by eorroe** [comment]
Thanks, but I already use both of those, and was interested in the idea of the fuzzy search part. So was trying that one out.

Guess I'll just have to stick to those, I'll see if I can contact the creator of FFP
