### ISSUE TITLE
Add .gitignore icon?

### ISSUE THREAD

**Issue by Gabriel-p** [ctf0/Seti_ST3#185]
I noticed there's no icon for the `.gitignore` file. Be nice to have one.

**Comment by ctf0** [comment]
actually all the `.git` should have an icon already as shown in the screen shots

**Comment by Gabriel-p** [comment]
But that's the `.git` folder (hidden by default in Sublime), not the `.gitignore` file.

**Comment by ctf0** [comment]
its for the `.git files` not the `folder` because the dot folders are hidden by the system not by ST, also the icon should display for any `.git* files`

**Comment by ctf0** [comment]
check https://github.com/ctf0/Seti_ST3/blob/master/Langs/Git.tmLanguage , thats are the git files that the theme currently support, also install https://packagecontrol.io/packages/Dotfiles%20Syntax%20Highlighting to have smoe HL in your git files.
