### ISSUE TITLE
Tabs are not effected as like screenshot

### ISSUE THREAD

**Issue by himelkazi** [ctf0/Seti_ST3#186]
Hi,
Thank you best sublime text's theme's package. I installed it but I can't make my tab like quadrilaterals as like your second screenshot. I also can't able to appear blue BORDER-BOTTOM in the active tab. How to do that ? Hope I will helped by your
Regards

**Comment by ctf0** [comment]
for the square tabs activate the `Seti_orig.sublime-theme` and the blue bar should be active by default unless you use   `"Seti_no_blue_bar": true` which will remove the blue bar under the un-saved tabs.

**Comment by himelkazi** [comment]
wow ! got it ! many many thanks for giving my editor a stunning look :)

**Comment by himelkazi** [comment]
wow ! got it ! many many thanks for giving my editor a stunning look :)
