### ISSUE TITLE
Unable to add Seti UI icons to Numix Dark Blue theme on sublime text 3

### ISSUE THREAD

**Issue by DevilReactor** [ctf0/Seti_ST3#187]
instead it shows this
![capture](https://cloud.githubusercontent.com/assets/15311796/10818663/6735c204-7e69-11e5-9d0f-180ccd4b3c27.PNG)

**Comment by ctf0** [comment]
because you need to open the files you copied to the new directory and change the paths :)

**Comment by DevilReactor** [comment]
I don't understood as I'm a newbie and I searched a lot on google...

what I have done first install numix theme and than add urs seti icon to 
user/Numix theme folder but nothing works

On 10/30/2015 7:19 PM, Muah wrote:
>
> because you need to open the files you copied to the new directory and 
> change the paths :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ctf0/Seti_ST3/issues/187#issuecomment-152530863>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by ctf0** [comment]
from what i can see that you copied more than the icons as the tabs has changed as well, anyway what you need it only copy the folders `icons+Langs+Prefs` to the new theme folder and restart it.

**Comment by DevilReactor** [comment]
this is what I have done 
1: user preference 
![capture](https://cloud.githubusercontent.com/assets/15311796/10862028/202f1b02-7fbe-11e5-8cbc-8214109cf520.PNG)

2:in Browse package 
![capture](https://cloud.githubusercontent.com/assets/15311796/10862031/3b968a56-7fbe-11e5-92e5-8139ecfcaafd.PNG)

3: inside numix dark blue folder
![capture](https://cloud.githubusercontent.com/assets/15311796/10862039/683069a6-7fbe-11e5-947c-f03cd1a69259.PNG)

4:inside user/Numix Dark Blue folder
![capture](https://cloud.githubusercontent.com/assets/15311796/10862040/906624ec-7fbe-11e5-838d-ee378f5da0f8.PNG)

![capture](https://cloud.githubusercontent.com/assets/15311796/10862044/a4c8636e-7fbe-11e5-9411-7bb1cd5c1858.PNG)


this is all what i have done, I'n not able to understood what I did wrong or where the heck is that bug :( 
pls help me solve this issue SIR

**Comment by ctf0** [comment]
copy folders `icons & Langs & Prefs` to `Packages\numix dark blue` and thats it, anything else it related to the numix theme folder name , check any of the files in the No.3 to figure the right name of the theme folder.

**Comment by DevilReactor** [comment]
Thnx it helped me
