### ISSUE TITLE
No highlight for modified tabs

### ISSUE THREAD

**Issue by snater** [ctf0/Seti_ST3#189]
I have `highlight_modified_tabs: true` and `theme: Seti.sublime-theme`, modified tabs not highlighted. With `Seti_orig` everything is ok. Sublime build - 3083.

**Comment by ctf0** [comment]
if you are using a `Retina` then yes it wont show up as i didn't make them, but i will upload the fix very soon.

https://github.com/ctf0/Seti_ST3/issues/148

**Comment by snater** [comment]
No, I have Air with 1440x900

**Comment by snater** [comment]
Both are modified 
![modified-tabs](https://1.downloader.disk.yandex.ru/preview/640033da86722c2ba07084ee4a0e7f5b76daa91c5dde26ee713120b2542d1f26/inf/auYrE4lsHhnxmeLGc8IDoRHKcLZmjyvHx9PEtl-A38Bp47H-lZSHhLyiMz9cLMpQSIDCudbJ5rOkrQCHd6I8VA%3D%3D?uid=0&filename=2015-11-10%2011-42-33%20%20mnt%20mm%20blocks%20desktop%20advanced-statistic%20advanced-statistic.js%20%E2%80%94%20mm.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=XXL&crop=0)

**Comment by snater** [comment]
I just figured out, problem is I had `"show_tab_close_buttons": false`. Could you make highlight visible with this option like in `_orig`?

**Comment by ctf0** [comment]
am sorry am lost, you just need to make `"show_tab_close_buttons": true,`

**Comment by snater** [comment]
yes, but in `Seti_orig` I can disable `close_buttons` but still remain highlighting
![hightlight no close](https://3.downloader.disk.yandex.ru/preview/4d93aa77063a5cd76e1e71466edb5504965f3707f6ad1ee53806ca56a88b5840/inf/H-lVSmvWoc-d-3XAJ2s_YJf-eNJ7ww9cFdYFA0oF3WVeT9I8XwYPz49pjPGqxax5J7O8yxwG3K6J539fu9RFfw%3D%3D?uid=0&filename=2015-11-10%2013-18-06%20%20mnt%20mm%20blocks%20desktop%20application-select%20application-select.js%20%E2%80%94%20mm.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=XXL&crop=0)

**Comment by ctf0** [comment]
because you need to also add `"highlight_modified_tabs": false,` as the circle icon is an indicator of the unsaved view.

**Comment by snater** [comment]
wait, but I want to have `highlighting`) To clearify - I need to remaing modification highliting but disable close buttons

**Comment by ctf0** [comment]
am sorry i have no idea what are you talking about.
