### ISSUE TITLE
Error with Seti_orig

### ISSUE THREAD

**Issue by alissonbovenzo** [ctf0/Seti_ST3#203]
In the last update, Seti_orig.tmTheme removed the file from the folder Scheme and I can no longer use it after it...
 has been modified using the style package?

[]'s

**Comment by ctf0** [comment]
yeap, as stated in the last update message, i removed all except seti_monaki as the current seti scheme is a total mess and i thought it would be better to get rid of it till its fixed which will take some time but i will bring it back asap.

**Comment by alissonbovenzo** [comment]
Ohhh sure, no problem
Per hour i have used this package with themr! :)

tks sir :)

[]'s

**Comment by ctf0** [comment]
np, btw they are now included under `Mod` branch till its included in the `Master`
