### ISSUE TITLE
Why are the schemes are gone?

### ISSUE THREAD

**Issue by txtsd** [ctf0/Seti_ST3#204]
`Seti.tmtheme` and `Seti_orig.tmtheme` used to be in the `Schemes` folder. Both are gone with the latest update.

`Seti_orig.tmtheme` is my favorite. Please bring it back.
![Why are the schemes are gone?](http://i.imgur.com/SKfHJoQ.png)

EDIT: Just saw the update message (It didn't pop up after the update)
Removing the colorschemes is **NOT** the correct way of fixing the problem. Re-include them, and release updates whenever you can.

**Comment by ctf0** [comment]
can u wait till next sunday, i will upload the fixed one and will include the old under the `Mod` branch

**Comment by denji** [comment]
@ctf0

![seti tmtheme](https://cloud.githubusercontent.com/assets/3759759/11996946/d12a79f4-aa77-11e5-9d4c-194df75dce8f.png)

**Comment by txtsd** [comment]
No problem. I copied the schemes back from the backup folder. Looking forward to `seti_orig` scheme updates!
`seti_monokai` will look not-so-bad if you make the background color match with the rest of the UI.

**Comment by ctf0** [comment]
will look into that, thanx for the idea.

**Comment by NekR** [comment]
> can u wait till next sunday,

lol, and stop working? do you realize people use ST3 for work?

**Comment by denji** [comment]
Seti_ST3 stable deprecated.

**Comment by ctf0** [comment]
@NekR i didnt realize that ppl actually like that scheme that much specially that the colors are way off for many scopes.

@denji have no idea what u just said mean.
