### ISSUE TITLE
Color schemes removed ?!!

### ISSUE THREAD

**Issue by christophelimpalair** [ctf0/Seti_ST3#207]
I just updated and now my theme is all messed up. It says "Error loading colour scheme Packages/Seti_UI/Scheme/Seti.tmTheme: Unable to open Packages/Seti_UI/Scheme/Seti.tmTheme"

So I renamed my Seti_monokai.tmTheme to Seti.tmTheme to get rid of the error, but it hasn't gone back to monokai

**Comment by NekR** [comment]
Samething, seems that there is only `"Packages/Seti_UI/Scheme/Seti_monokai.tmTheme"` in latest update. You really did it bad. I had opened 6 projects and had to close them because I wan't able to stop Sublime displaying errors and coolers of my Macbook became crazy like sublime is doing millions of millions operation in a sec.

**Comment by ctf0** [comment]
from the latest update notes
`9. the Seti Scheme atm is a big mess , so all are removed except "Seti_monokai"`
but as it seems that many are messing them i will put them back till they are fixed.

**Comment by NekR** [comment]
@ctf0 hmm.. you really shouldn't do that without notice. Update notes doesn't really help since Package Control auto updates Seti by some reason.

**Comment by ctf0** [comment]
@NekR one of the new strange reasons is that Package Control doesn't wait the 1 hour like it used to, neither it only updates when a new tag is pushed.

anyway here is the folder to get the schemes back incase anyone came through this issue
https://github.com/ctf0/Seti_ST3/tree/Mods/Scheme

**Comment by NekR** [comment]
@ctf0 thanks, this works for me. Btw, what is wrong with those themes and why they are broken?

**Comment by ctf0** [comment]
@NekR u mean the schemes, because they were based on `Neon` which if far from ideal for this particular project, u can check the original HL on atom and u will see what i mean.

**Comment by christophelimpalair** [comment]
Downloading files fixed it for me. It automatically updated so I didn't even get a chance to read the update notes. Thanks.

**Comment by ctf0** [comment]
@christophelimpalair i believe u should stick to this wayaround fix as i removed all the schemes from the package till the original scheme is correctly ported.

**Comment by erdemapaydin** [comment]
why do you keep updating the package if the schemes are broken?
if you update the package, and sublime downloads it, it overwrites any changes to the package folder, which includes the missing scheme files that i have to add manually after every update.
if you are going to update the package, you should prioritise this issue, instead of fixing other things that break the package again and again.
thx

**Comment by ctf0** [comment]
- first the schemes have nothing to do with the updates i push
- secondly as stated b4 u can download the schemes and put them anywhere other than the seti theme folder and ur work wont get effectd.
- third the scheme file aint that easy to implment and to get it as a 100% same as the original port is just a pain in the butt, which i numerously stated that we need someone to do as i have many other things to do.
- forth , all the updates am pushing those 2 days were just a 0 day fixes so i dont need to tackle that later on.

**Comment by TiagoDanin** [comment]
Seti_UI not worked correctly here too :(
![image](https://cloud.githubusercontent.com/assets/5731176/12054962/0376f4ee-af07-11e5-89f2-0668f23933ca.png)

**Comment by appliaison** [comment]
I am experiencing the same error

"sublime unable to open Packages/Seti_UI/Scheme/Seti_monokai.tmTheme"

**Comment by appliaison** [comment]
Fixed by removing the color_scheme line in Preferences.sublime-setting (Preferences -> User-Settings) so it looks as follows
`
{
	"font_size": 16,
	"ignored_packages":
	[
	],
	"open_files_in_new_window": false,
	"theme": "Seti.sublime-theme"
}
`

**Comment by domark0721** [comment]
I have the same problem...

**Comment by leozhang2018** [comment]
@domark0721 
You should download the schemes from here https://github.com/ctf0/Seti_ST3/tree/Mods ,and copy files into package/Seti_UI,rewrite the Preferences.sublime-settings
Don't forget to check the README :)

**Comment by ctf0** [comment]
as it seems that no one actually read, so in the next update i will include the scheme link in the readme.

**Comment by markphd** [comment]
For those getting error `Unable to open Packages/Seti_UI/Langs/Gulpfile JS.tmLanguage` , you can download the Langs folder from here: https://github.com/immanuelsun888/Seti_ST3/tree/master/Langs

**Comment by ctf0** [comment]
@markphd this is related to the new folder structure, just clear ur cache folder and it will work without any probs :)

**Comment by AlexVentura** [comment]
Hey I just have reinstall OS X from scratch I then I install ST3 but now I can't see the **Packages/Seti_UI/** folder. So I'm not able to locate the folder to put the *theme* files `Packages/Seti_UI/Scheme/Seti.tmTheme`. I just look like in two colours but I need to edit the `Seti.tmTheme` file in order to add and set my own colours.

Thins is my config file. But as you can see working area and sidebar have different colours, I hate that.

<img width="1552" alt="screen shot 2016-01-04 at 16 00 15" src="https://cloud.githubusercontent.com/assets/13169164/12101888/d3a9bce8-b2fc-11e5-80dd-93d71c8bf0e3.png">

Does any body know how to solve this?

**Comment by markphd** [comment]
@AlexVentura did you install it manually? If so, you might be experiencing this [StackOverflow issue](http://stackoverflow.com/questions/29257763/sublime-text-3-deleted-my-folder-under-packages) where theme folder is automatically removed.

Otherwise, check if you can select the color scheme from `Preferences > Color Scheme > Seti_UI` and if theme is not listed, try reinstalling it via Package Manager.

**Comment by AlexVentura** [comment]
Hi @markphd I have installed it from `Package Manager` but it does not aper on the preferences menu:

![untitled](https://cloud.githubusercontent.com/assets/13169164/12108359/8afa80d2-b33c-11e5-938a-2acc86172e99.png)

**Comment by ctf0** [comment]
@AlexVentura because what @markphd meant is that u make a new folder inside packages and put the scheme files u download in that folder then u will find it in the menu pref as right now u r only viewing the ones that comes pre-installed with sublime.

**Comment by mkstix6** [comment]
@ctf0 kindly pointed me to the old files here: https://github.com/ctf0/Seti_ST3/tree/Mods/Scheme

I dropped them into:
Users > [USERNAME] > Library > Application Support > Sublime Text 3 > Packages > User

They then appeared in Sublime Text under Preferences > Color Scheme > User

Job done.

![screen_shot_2016-01-05_at_15_29_38](https://cloud.githubusercontent.com/assets/1573136/12119131/c58e3aec-b3c1-11e5-9400-1ff576a72ae3.png)

**Comment by AlexVentura** [comment]
Thanks @ctf0 I have done what @mkstix6 and now everything seems to be working fine!
I have another question, what about updates? Does it will make ST3 crashes after update?

**Comment by ctf0** [comment]
nop, the updates will continue changing the files **inside** the seti folder, have **NO** business what-so-ever about anything else outside that folder

**Comment by ivenspontes** [comment]
I made a backup of the file Color Scheme - Default.sublime-package , then I rename the file to Color Scheme - Default.sublime-package.rar , I opened it and put the 3 files in, rename it to the standard, and now it's functioning normally.

![monokai](https://cloud.githubusercontent.com/assets/2898158/12540809/011b0664-c2ed-11e5-868a-cb62f25201df.png)

**Comment by ctf0** [comment]
@ivenspontes its up to u, but u simply could have just copied those files to the `Packages > User` and they would have appeared

**Comment by ivenspontes** [comment]
@ctf0 it is more easy, I had not seen his tutorial. thx

**Comment by NekR** [comment]
With new sublime release, Seti and Seti_orig schemes look completely awful :(

**Comment by ctf0** [comment]
i havent install the latest yet but will fix this soon

**Comment by NekR** [comment]
![image](https://cloud.githubusercontent.com/assets/1189265/12916883/631b7fe4-cf3e-11e5-8047-c4fbe4e2fac4.png)

At least something wrong with JS syntax. Double checked in my packages, nothing altering JS highlighting, but I may be wrong.

**Comment by ctf0** [comment]
what about our other schemes, does they have the same issue ?

**Comment by NekR** [comment]
@ctf0 Seti and Seti_orig has this. Seti_monokai is okay. Do you have any other schemes?

**Comment by AlexVentura** [comment]
I have some issues with the new release of ST3:

* It is not colouring the `else` and `else if` syntax:

<img width="572" alt="screen shot 2016-02-09 at 12 18 09" src="https://cloud.githubusercontent.com/assets/13169164/12926111/728c362e-cf27-11e5-8095-8d294e422d36.png">

I don't like the new highlighting colors.
**So how can I change to the old ones?**

**Comment by ctf0** [comment]
@AlexVentura actually i havent changed anything in that scheme in ages nor i ported the original one yet, also i haven't install the latest dev build yet to test the issues mentioned above.

anyway give me some time and i will see what i can do about it, another trick will be introduced soon which will make things much more fluid for the users UI wise.

**Comment by NekR** [comment]
@ctf0 not a latest dev build, latest stable build with new `.sublime-syntax` feature, i.e. extended syntax highlighting, it broke the things.

**Comment by ctf0** [comment]
@NekR can u do the changes and send me a PR ?

**Comment by NekR** [comment]
@ctf0 if I knew how to do it. I have no idea how old syntax highlighting works and even how new, sorry. Just know that they migrated to that new thing.

**Comment by ctf0** [comment]
yes i know but i was using the dev builds till 3101 and all was good ,anyhow i will see what changed and will update accordingly.

**Comment by AlexVentura** [comment]
@ctf0 Allright I will be waiting for the update to fix that issue. Because my comments `// Comment` under `else` or `else if` don't seem to work fine and it looks pretty awful.
Thanks in advance!

**Comment by dingo-d** [comment]
After the latest update theme looks awful :S The colors are dreadful:

<img src="http://i.imgur.com/KcZolyE.png" />

The green on methods on ajax and the dropdown for suggestions :\ Any fix for this? Can we manually change these colors and bolding of the fonts?

**Comment by ctf0** [comment]
plz any issues related to the color being changed in the scheme files, report them at https://github.com/ctf0/Seti_ST3/issues/231

**Comment by kuldeepdaftary** [comment]
Managed to fix this by installing a new package called `Seti_UX`

Once you install the package, goto : Preferences >  Color Scheme > Seti_UX > Seti
