### ISSUE TITLE
Inactive tabs remains bold

### ISSUE THREAD

**Issue by tushortz** [ctf0/Seti_ST3#208]
Hello, First, I would like to say, you guys did a great job. That being said, a once active tab remains bold irrespective of when ti becomes inactive. Is there a way to fix that without removing its settings .

**Comment by ctf0** [comment]
can u send me a screen shot with what exactly setting have u used so i can reproduce ?

**Comment by tushortz** [comment]
![preview](https://cloud.githubusercontent.com/assets/13158672/12004220/8fdb42a8-ab3f-11e5-816d-b9c2313dba92.png)

As you can see from the screenshot, the 'preferences.sublime-settings` is bold because it is active. Even the `Runserver.java` is in bold even though It's no more the active pane. 

The line that makes the active pane bold is `line11`

**Comment by NekR** [comment]
hmm.. why tabs now are looking as default tabs? e.g. rounded corners. Is there a way to bring back square tabs with border-line at bottom?

**Comment by ctf0** [comment]
ah yes, the tab label become bold once its selected, i will fix that.
