### ISSUE TITLE
`Goto Anything` input box  is kind of huge

### ISSUE THREAD

**Issue by simov** [ctf0/Seti_ST3#209]
![find-in-files](https://cloud.githubusercontent.com/assets/1694112/12003703/a2fca1ee-ab33-11e5-9f16-78ace9a65c9c.png)

Definitely looking weird to me. I'm using `Seti_orig` theme, and a few days ago the find in files text area become unreasonably tall, any ideas?

**Comment by ctf0** [comment]
can u tell me what exactly is the steps for me to reproduce that ?

**Comment by simov** [comment]
Check out the [File Navigation and File Management](http://docs.sublimetext.info/en/latest/file_management/file_management.html) - on Linux it's `Ctrl+P` to activate it, `Ctrl+R` and the rest of the variations.

I also updated the issue's title.

**Comment by ctf0** [comment]
ah yes, the whole panel is now larger than it used to be for easier navigation and better readability, but its not that big even on my 15" lap, try this
use `ctrl+shift+p` and send me a screenshot of the whole screen,

**Comment by simov** [comment]
![screenshot from 2015-12-25 22 15 50](https://cloud.githubusercontent.com/assets/1694112/12004279/1c7f6968-ab55-11e5-9f31-000f1b3c5c6e.png)

22" 1680x1050 I didn't had any problems with this control up to this point, so I'm assuming you are talking about high res retina displays?

And yes, this is looking very weird on my end. BTW the mouse hover styles are gone too, can't remember if they actually were there, because I'm using the keyboard most of the time.

If that's a fix for high res displays, then an option to configure that size should be the way to go, I think.

**Comment by zhulongzheng** [comment]
It also feels weird to me about this huge input box, and texts in it are not vertically center.
![sublime-seti](https://cloud.githubusercontent.com/assets/5362563/12005537/2a2c973a-abe5-11e5-996f-f9245122176c.png)

**Comment by ctf0** [comment]
@simov actually no i was talking about the normal 1366x768 15" laps, however i will look into making an option to make the panel smaller than the current, 

and for the hover state, yes its removed from all the panels as it was mostly distractive.

**Comment by ctf0** [comment]
@zhulongzheng yes i understand but having the txt vertically center wasnt in my intention , however i will try to add an option to bring the panel back as b4.

**Comment by ctf0** [comment]
option will be added under `Seti_panel_nrml` in the next update.

**Comment by simov** [comment]
thanks :+1:

**Comment by zhulongzheng** [comment]
thanks :+1:
