### ISSUE TITLE
No color scheme ??

### ISSUE THREAD

**Issue by Mandras** [ctf0/Seti_ST3#210]
Left column still has right colors and icons, but I still have monokai color scheme, ands there is no new color scheme after the installation (from package control).
I'm using ST3 build 3083

**Comment by ctf0** [comment]
i have no idea what u mean about the left column but for the schemes yes they are all removed as stated here 
https://github.com/ctf0/Seti_ST3/issues/207
and for the update notes
`2. all schemes are removed, if u still want them back u can find em on `Mod` branch.`

**Comment by Mandras** [comment]
Sorry if u do not understand, my english is pretty poor :/
Can you explain me how to get the color scheme as I can see at your screenshots please

**Comment by ctf0** [comment]
its okay, the thing is that i have removed all the scheme files and if u want to use any of them u can download any separately from https://github.com/ctf0/Seti_ST3/tree/Mods/Scheme

**Comment by Mandras** [comment]
Work great !
Thank you, scheme is amazing !
