### ISSUE TITLE
Error Loading Language File

### ISSUE THREAD

**Issue by brennebeck** [ctf0/Seti_ST3#211]
After most recent update I'm getting the following: 

```
Error loading syntax file "Packages/Seti_UI/Langs/Git.tmLanguage": Unable to open Packages/Seti_UI/Langs/Git.tmLanguage
```

I looked in the recent issues and didn't see anything similar. 

Seti is installed via Package Control, but I'm about to try uninstalling it and installing via git.

**Comment by brennebeck** [comment]
Oddly enough, I get the same error regardless of which custom theme I use, have no folder `Packages/Seti_UI` and am unsure where this is being called from.

**Comment by ctf0** [comment]
i think u should clean up the `Cache` folder, as the folder structure in the latest update has changed.
