### ISSUE TITLE
Panel and Scrollbar background color

### ISSUE THREAD

**Issue by simov** [ctf0/Seti_ST3#212]
:wave: 

I think the slightly darker background color on the panels worked better for me. I mean that may be just me, but I use really high contrast themes and syntaxhighlighting, so white text on gray background is not as striking and it's harder for me to see it.

![projects](https://cloud.githubusercontent.com/assets/1694112/12015901/2f81ebdc-ad4c-11e5-8fb1-63129b4c7e88.png)

Same for the scrollbar's background color (not the handle itself), but the opposite - the slightly darker background worked better for me (although it was really hard to see), because right now they are too bright for my setup.

![screenshot from 2015-12-28 10 22 24](https://cloud.githubusercontent.com/assets/1694112/12015943/1319052e-ad4d-11e5-96ac-87e9c3968fe2.png)

**Comment by simov** [comment]
Hmm I'm actually looking the issue tracker through the [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark) theme, so my screenshots are looking differently :)

**Comment by simov** [comment]
![dark2](https://cloud.githubusercontent.com/assets/1694112/12016023/7064729e-ad4e-11e5-8969-31156aaa6ce3.png)


![dark](https://cloud.githubusercontent.com/assets/1694112/12016016/50cd98ca-ad4e-11e5-93a9-9c145c36b69a.png)

I think that way you can see how the scrollbar background color is sticking out too much.

**Comment by simov** [comment]
One last thing - the tabs x close button got brighter too, I guess all of these are too much for separate options, but I just wanted to point them out.

**Comment by ctf0** [comment]
thanx for the headsup, but am kinda lost, what exactly u want to change ?

**Comment by simov** [comment]
- Panel background color is too bright (go to anything, switch project etc)
- Scrollbar background color is too bright
- Tab x close buttons are too bright

Basically these 3 things were a bit darker in the previous version, can't tell you the exact colors.

**Comment by ctf0** [comment]
will see about that today.

**Comment by ctf0** [comment]
the panel is the same as it used to be so i wont change it,
the scroll bar bg is back as it was,
the tab x, plz send me the hex for the shade u want.

**Comment by simov** [comment]
#### Tab x close button

I just changed the `layer0.opacity` for `Tab close button` to `0.5` in `Seti_orig.sublime-theme` and it's back to normal.

#### Go to anything, Switch Projects

> changed the "GoTo anything" & "Code Compilation DropDown" panel color to match the quick panel, i overlooked those the first time.

That's your words from the changelog, so it wasn't that way.

#### Scrollbars

Thanks :+1:

**Comment by simov** [comment]
BTW the panel backgrounds and the scrollbar background are now probably matching your overall theme, so if there is a way to change those styles easily through an option, that would be great. Because you know someone may want to have them brighter.

**Comment by ctf0** [comment]
the thing is for `Go to anything, Switch Projects` they were using the old tints which was brown and it was distractive, but now all the panels have a one unified color.

**Comment by simov** [comment]
Like I said the current backgrounds match your overall theme better, but distracting is subjective. So it's better to give your users the ability to choose for themselves.

Can you tell me which values are related to these background colors?

**Comment by ctf0** [comment]
right now the panel it self is an img so having this an option for each user is not an option, but for changing the selected row and the row colors, start from the `//  PANEL BACKGROUNDS` down.

**Comment by simov** [comment]
Yep I found them. I'll give this new background color a chance (panels + scrollbars). I'm getting your point with the colors, I think the autocomplete panel was with brighter background color, but I have mine disabled so it wasn't bothering me.

I just dimmed the tab close button and enabled the hover state for the folders inside the sidebar.

**Comment by ctf0** [comment]
now just send me a pr with the close button.
