### ISSUE TITLE
New schemes structure

### ISSUE THREAD

**Issue by skechboy** [ctf0/Seti_ST3#213]
Hi,

I've noticed that with the recent update you've "removed" https://github.com/ctf0/Seti_ST3/commit/d42b3be0a7a75299a25cfcacda50d00d48c15434 all schemes from the theme.

For those concerned users you can find them in "Mods" branch and install them https://github.com/ctf0/Seti_ST3/tree/Mods it relatlivley easy to install your color scheme manually. All you need to do is create Scheme folder within the theme folder in packages and add the scheme file you like. 

However  what is concerning me what happens when new update is released, do we need to do the same thing with each new update?

**Comment by ctf0** [comment]
no, just put those schemes anywhere other than the seti_ui folder and load them normally, now when a new update is pushed this wont get effected in anyway :+1:
