### ISSUE TITLE
Folder hover state in sidebar is missing

### ISSUE THREAD

**Issue by simov** [ctf0/Seti_ST3#214]
I'm pretty sure there was a hover state for the folders in the sidebar, or probably I'm hallucinating. Now only the file names get slightly brighter on mouse over.

**Comment by ctf0** [comment]
yes u r correct, again that was stated in the update notes which i have no clue why its not showing on update :(

**Comment by simov** [comment]
I just uncommented that line in `Seti_orig.sublime-theme`, this degrades the usability of the theme, but then again it's a matter of opinion if it's about design, right.

**Comment by ctf0** [comment]
i may add it back later.

**Comment by simov** [comment]
Your call, but consider adding this as option or something. What's distracting to you may be useful to others.
