### ISSUE TITLE
SVG icon

### ISSUE THREAD

**Issue by yoanmalie** [ctf0/Seti_ST3#217]
Please, add SVG icon, because it look like RSS or Wifi icon
![image](https://cloud.githubusercontent.com/assets/3357171/12050599/ce15e65c-aef7-11e5-9c7a-2439d65586e8.png)

**Comment by ctf0** [comment]
because svg is xml ,so it have the same icon for xml, but honestly i was going to make it the same icon as the images but then left as it is to avoid confusion.

**Comment by yoanmalie** [comment]
Or by simply changing this icon that is too specific and reminds me RSS ?

**Comment by ctf0** [comment]
yes i understand, if u have a better one ,send me the vector file for it and i will make it

**Comment by yoanmalie** [comment]
SVG has a logo, we can use it:
http://www.w3.org/Graphics/SVG/svglogo.svg

There also some alternatives on the web, like this one:
https://fr.wikipedia.org/wiki/Scalable_Vector_Graphics#/media/File:SVG_Simple_Logo.svg

**Comment by ctf0** [comment]
i found something better, get the latest update and tell me what u think

**Comment by yoanmalie** [comment]
Nothing changed for me, i see the same icon

**Comment by ctf0** [comment]
clear the cache folder, and install the new `XML` setting file i included inside the `Ext` folder
