### ISSUE TITLE
Tab label hover state is missing

### ISSUE THREAD

**Issue by pkq** [ctf0/Seti_ST3#219]
In previous versions of the theme, there was a hover state for the tab labels. Was that removed intentionally? What setting(s) control that behavior? I thought this

    {
        "class": "tab_label",
        "parents": [{"class": "tab_control", "attributes": ["hover", "selected"]}],
        "fg": [255, 255, 255],
        "font.bold": false
    },

would do the trick, but it doesn't seem to...

**Comment by ctf0** [comment]
the hover state is there, the reason u cant notice it is that the difference between the main and the hover is the slight change in the alpha channel

**Comment by pkq** [comment]
So how do I get the more obvious "highlighting" effect that was there previously?

**Comment by ctf0** [comment]
check the part `//  TAB LABELS` and change the settings till it fits ur need and send me a PR

**Comment by pkq** [comment]
Yeah, I've been messing with that section for over an hour now, but nothing I try seems to have any effect on the hover state of the unselected tabs. Any ideas?

**Comment by ctf0** [comment]
ah yes, because the unselected doesnt have aone , only the selected

**Comment by pkq** [comment]
That makes sense, thanks. Just submitted a pull request.

**Comment by pkq** [comment]
Thanks!
