### ISSUE TITLE
Seti and Seti_orig not showing retina close icons in tabs

### ISSUE THREAD

**Issue by valentinocossar** [ctf0/Seti_ST3#221]
Both Seti_orig.sublime-theme and Seti.sublime-theme are not using retina close icons in tabs. In the Mod branch the icons are used in Seti.sublime-theme file, but not in the latest version in the master branch. Why the icons are not more used?

<img width="271" alt="schermata 2016-01-03 alle 23 09 51" src="https://cloud.githubusercontent.com/assets/4087384/12081238/793cfa7e-b273-11e5-9a04-42e24b1b0b88.png">

**Comment by ctf0** [comment]
i can update it but the issue is that i dont have a retina to test with, so i used the standard instead.

**Comment by valentinocossar** [comment]
Can I help you to make tests in some way?

**Comment by ctf0** [comment]
yes sure, i will update it today and ping u once its pushed

**Comment by valentinocossar** [comment]
Okay, thanks!

**Comment by ctf0** [comment]
sorry for the delay, i have updated the repo,plz check now :)

**Comment by valentinocossar** [comment]
Thank you for the help, I've just finished to test the themes (Seti and Seti_orig) and seem to work fine with the new icons. Do I have to look something in particular, maybe using particular options in "Preferences.sublime-settings"?

**Comment by ctf0** [comment]
no, thats it, enjoy :)
