### ISSUE TITLE
Missing tabs

### ISSUE THREAD

**Issue by simov** [ctf0/Seti_ST3#223]
![missing-tabs](https://cloud.githubusercontent.com/assets/1694112/12220501/4f0e7d0e-b77d-11e5-871c-9ccc1a08b0ed.png)

:wave: I recently noticed something weird. First of all, as you can see in the screenshot one tab is half shown, but what's even worst - the last open tab is completely hidden!

I have been using similar setup (split pane + directory sidebar) for a long time and I only recently noticed this issue.

**Comment by simov** [comment]
Just commented out `"tab_min_width": 95,`, again this change makes the theme unusable for me.

It's better to leave the user to decide how many tabs he can actually handle, instead of just breaking the theme, because hidden tabs is exactly that.

**Comment by ctf0** [comment]
can u test with more tabs and see if ur solution still applies ?

**Comment by simov** [comment]
![moar-tabs](https://cloud.githubusercontent.com/assets/1694112/12220705/d266ef22-b784-11e5-9709-077015f2a442.png)

Yep, seems to be working, I can submit a PR if you want.

**Comment by ctf0** [comment]
actually what tab_min_width does it to control how many tabs to show on the tab bar, so if u removed it ST will fall back to its default , but what u can do is u can try to change the value to something bigger and see if it does what u want

**Comment by simov** [comment]
I'm not sure I'm getting your point here. Commenting it out results in the default behavior, and that's what I want - I want to be able to open as many tabs as I want (let's say 50) and I wan't to see all of them, even though they are tiny.

I don't think that the default theme have any `tab_min_width` set.

**Comment by simov** [comment]
That might be related to `enable_tab_scrolling` setting actually? But I have my set up to `false` as you can see from the screenshot.

**Comment by ctf0** [comment]
mmmm, how about leaving the `min_width` and make a new setting with what u want and send me the PR.

**Comment by simov** [comment]
Ok, I'll look at it ASAP.
