### ISSUE TITLE
Gulpfile.tmlanguage error

### ISSUE THREAD

**Issue by ysfjwd** [ctf0/Seti_ST3#225]
lately i have been getting this error
```
error: Error loading syntax file "Packages/Seti_UI/Langs/Gulpfile JS.tmLanguage": Unable to open Packages/Seti_UI/Langs/Gulpfile JS.tmLanguage
```

//ysf

**Comment by ctf0** [comment]
because the folder has new structure, so plz remove the cache folder for seti and it should work as expected.
