### ISSUE TITLE
no icons on sidebar panel

### ISSUE THREAD

**Issue by surajsingh-itian** [ctf0/Seti_ST3#230]
![sublime](https://cloud.githubusercontent.com/assets/16804455/12962429/47c3bddc-d06b-11e5-99de-cb13525401c2.png)
Side not icons are as expected with default theme preset
<img width="1280" alt="screen shot 2016-02-11 at 2 56 32 am" src="https://cloud.githubusercontent.com/assets/16804455/12962466/7b51dae4-d06b-11e5-865c-96bc7ef3b350.png">
When following theme setting is specified
"theme": "Seti.sublime-theme",
  
    "caret_extra_width": 2,                 //  to have a wider/thicker caret
    "caret_extra_bottom": 3,                //  to make the caret = to the line height (the theme currently support 0,3,5)
    "caret_extra_top": 3,
    "overlay_scroll_bars": "enabled",       //  to show scrollbars only when scrolling
    "highlight_line": true,                 //  to highlight the current line

Icons show but still not as expected, theme is modified
<img width="1280" alt="screen shot 2016-02-11 at 2 56 37 am" src="https://cloud.githubusercontent.com/assets/16804455/12962505/b614b610-d06b-11e5-8ccf-f29af77a97f3.png">
I have tried Package Control & Manual both option.

**Comment by ctf0** [comment]
the second ss is having the correct icons, whats the issue then ?

**Comment by surajsingh-itian** [comment]
I expected it to work with default Black theme.

not only that if I revert to default SS 1 the icons are messed up (most of the file are not having icons)

**Comment by ctf0** [comment]
this is because the default theme doesnt have support for different file extensions, however if u still want to have that support u can simply create a folder call `Theme - Default` in ur packages folder then copy the `icons` folder from seti to the above folder.

**Comment by surajsingh-itian** [comment]
Working now Thanks
