### ISSUE TITLE
Colors changed after updating ST3 to build 3103

### ISSUE THREAD

**Issue by Sastidar** [ctf0/Seti_ST3#231]
Well today once I opened up sublime it requested to update, and so it did. Then after the restart the colors mostly inside js files are different.., Is this normal or the theme needs update? bellow are my user settings which used to work great till the update occurred.

``` json
{
    "caret_extra_bottom": 3,
    "caret_extra_top": 3,
    "caret_extra_width": 2,
    "color_scheme": "Packages/User/SublimeLinter/Seti (SL).tmTheme",
    "font_size": 12,
    "highlight_line": true,
    "ignored_packages":
    [
        "Vintage"
    ],
    "on_pre_save_user":
    [
    ],
    "overlay_scroll_bars": "enabled",
    "theme": "Seti.sublime-theme",
    "update_check": true
}
```

**Comment by ctf0** [comment]
it seems that many users are also having the same issue as u with the scheme files which i didnt touch in ages, it will take some times to get it fixed but in the meanwhile i would suggest to go with another scheme file for now.

**Comment by equinusocio** [comment]
isn't a bug. ST from the last official build 3103 use a new syntax system. @ctf0 you have to rebuild schemes for this release or 3dev builds

**Comment by ctf0** [comment]
@equinusocio actually the issue is not related to the new syntax rather its more related to the scopes names which some was changed in the new definition , anyway i will try to fix them soon

**Comment by haohcraft** [comment]
+1

**Comment by alissonbovenzo** [comment]
+1

**Comment by rodriguezmanu** [comment]
+1

**Comment by augustoabreu** [comment]
+1

**Comment by eduwass** [comment]
For anyone needing a quick workaround see https://github.com/ctf0/Seti_ST3/issues/207#issuecomment-169036505 
(worked for me)  

¯\\_(ツ)_/¯
