### ISSUE TITLE
No file icons from dev build 3106

### ISSUE THREAD

**Issue by equinusocio** [ctf0/Seti_ST3#232]
Just for info, from build 3106 all files icons doesn't work anymore. I will try to figure out how to fix this..

**Comment by Volox** [comment]
+1

**Comment by ctf0** [comment]
will get into that tonight

**Comment by ctf0** [comment]
right now the default theme doesnt have any file icons which i believe is related to the new mechanism of updating the new theme on the fly, for now i would recommend staying on 3105 and add `"update_check": false,`

**Comment by saadq** [comment]
Dev Build 3107 is out, and it seems to have fixed the regressions for the file icons and tabs.

**Comment by ctf0** [comment]
thanx for the heads up @saadq :metal:
