### ISSUE TITLE
tab separator

### ISSUE THREAD

**Issue by jessegilbride** [ctf0/Seti_ST3#236]
When tabs get too close, there's no way to distinguish their edges, making them look like a single tab.  (Screenshot attached.)

<img width="718" alt="seti_ui-tab-smush" src="https://cloud.githubusercontent.com/assets/5638513/14398254/bfb2d982-fdb0-11e5-9c3f-7748235bf11f.png">

**Comment by ctf0** [comment]
yes, thats because st overlap tabs on each other and as they all have the same color so they don't show up when overlapped , i will try to think of something.

**Comment by jessegilbride** [comment]
I seem to remember that the tabs are built with image files.  Perhaps the image for the left side of a tab could get updated to have a differentiation, something slick like the blue underline of the current file in view (this could look good with rectangular or rhomboidal tabs, but I digress).  I don't remember where I saw those images, but I found something similar: /Users/<username>/Library/Application Support/Sublime Text 3/Packages/Seti_UI/Main/

**Comment by ctf0** [comment]
yes i was thinking of adding like a subtle stroke or a light color over the sides of the tab but this will ruin the original look of the tabs, still i will try that and see how it would look

**Comment by ctf0** [comment]
@jessegilbride currently adding a border around the tabs wont looks good, also changing the tab_overlap to something smaller or even 0 wont fix the main issue , so unless there is an option or something to add to the theme to fix this, sadly i cant help with it.

**Comment by jessegilbride** [comment]
No worries.  Thanks for looking into it.

**Comment by va2m** [comment]
Add a border to the tabs, like 5%-15% darker (or lighter) of the background blue color.
See example with 15% darker and lighter.
Or perhaps  give the possibility to revert to the original tabs (from sublime text).
Like this, it does not work very well in UI terms it is confusing. 
Hope this helps!
![seti_ui-tabs-border-15 darker](https://user-images.githubusercontent.com/20317389/27427572-61c9f51c-5737-11e7-8dfa-5d15cc972865.png)
![seti_ui-tabs-border-15 lighter](https://user-images.githubusercontent.com/20317389/27427577-67c7c386-5737-11e7-8fbe-4d7562df77e9.png)

**Comment by ctf0** [comment]
@va2m can u add this to an option and send me a PR ?
