### ISSUE TITLE
Gray X mark instead of icons

### ISSUE THREAD

**Issue by kreynes** [ctf0/Seti_ST3#238]
I've been literally banging my head on the table trying to figure out why this is happening
http://puu.sh/p0kxT/733d38c53a.png
I'm running Build 3114.
Glad if anyone has any insights.

**Comment by ctf0** [comment]
try to drag the folder of the files in ST and u will get the icons, also if u r having something different on other theme plz send me a ss & the name of the theme

**Comment by kreynes** [comment]
@ctf0 Haven't tried any other theme, but dragging it didn't help :[

**Comment by ctf0** [comment]
well, the opened files is intended to be like that and u can only have the icons in the sidebar if u dragged a folder into ST

am using the same version of ST and have no issues what so ever.

**Comment by norbour** [comment]
I've got the same problem with sublime build 3114

**Comment by norbour** [comment]
@kreynes Hey, I got the icons by removing these two setting items in sublime text [settings-user]: "Seti_sb_no_icons": true,               
 "Seti_sb_blank": true,

**Comment by ctf0** [comment]
@norbour those settings will remove all the sidebar icons, not just the opened files ones.
