### ISSUE TITLE
Conflict with Sidebar Enhancements Package

### ISSUE THREAD

**Issue by benners00** [ctf0/Seti_ST3#239]
I cleared my Sublime text 3 (Build: 3114 / Windows) cache and install Seti_ST3 the scroll bars are fine. Once I install Sidebar Enahancements the scrollbars go too small to use and these settings make no difference.

"Seti_SB_med": true,
"Seti_SB_big": true, 

https://github.com/titoBouzout/SideBarEnhancements

Do you have a work around for this as SidebarEnhancements is an essential package. Thanks

**Comment by ctf0** [comment]
i just installed the same build along with the plugin and all working good, maybe u have another plugin conflicting with the theme or maybe u have `    "overlay_scroll_bars": "enabled"` ?

**Comment by benners00** [comment]
Yes, I do have `"overlay_scroll_bars": "enabled"`. If I disable it and restart Sublime it shows the scrollbars at the correct size. Ideally I'd like big, bright scroll bars only showing when I scroll. Is this possible?

**Comment by ctf0** [comment]
this is related to ST it self, it seems they made the overlay scrollbar have one default size no matter what else u have set, i believe we have to open a ticket over ST repo

**Comment by ctf0** [comment]
https://github.com/SublimeTextIssues/Core/issues/1221

**Comment by benners00** [comment]
Thank you. I think it would be a good addition to the theme if this worked as expected.

**Comment by ctf0** [comment]
i think it was working as it should in the older version of ST but cant rellay confirm, anyway hopefully it gets fixed soon.
