### ISSUE TITLE
Orange Scrollbars

### ISSUE THREAD

**Issue by dnuzum** [ctf0/Seti_ST3#240]
Much preferred the scrollbars not turning orange when scrolling. Is there a preference built in that can be flagged to false in the user preferences? Really hate using Themr. :)

**Comment by ctf0** [comment]
ah yes, i can turn back the old color, i thought maybe users would like some visual aid through the scrollbars.

**Comment by dnuzum** [comment]
I'm totally all about options for anyone! Maybe a flag like other options can be done?

**Comment by ctf0** [comment]
okay will add it by tmrw

**Comment by robertmain** [comment]
Came here to say this. It would be really nice if there was some way to set the colour of them (maybe a light blue)?

**Comment by ctf0** [comment]
@robertmain there is a light blue already in place `"Seti_SB_bright": true,   // brighter color for scrollbars`

**Comment by robertmain** [comment]
Oh right, cool. I didn't realise that "bright" referred to blue. Cheers.

**Comment by ctf0** [comment]
actually it would look better as the current state is more closer to the old seti scheme port blue.

**Comment by robertmain** [comment]
Regardless, it would be nice if the light blue that was used was consistent with the other shade of blue rather than having loads of different colours all over the place.

**Comment by Tibicenas** [comment]
Right now my scrollbars have more attention to my eyes than the code itself, kind o annoying, would be cool if we could setup this color, or at least a range of color

**Comment by ctf0** [comment]
i thought ppl would enable overlay scrollbars so they only show up when u scroll, anyway i will put back the old one today once i get home.

**Comment by robertmain** [comment]
TIL overlay scrollbars exist.... anyway, my only issue is the colour
inconsistencies

**Comment by ctf0** [comment]
okay got it, i will push the update today

**Comment by dnuzum** [comment]
Still getting Orange sidebars. False flag does not work to disable either. Appears to still be default.

**Comment by skechboy** [comment]
Same problem here

**Comment by ctf0** [comment]
all fixed now, sorry for that.
