### ISSUE TITLE
Angular Icon

### ISSUE THREAD

**Issue by Tibicenas** [ctf0/Seti_ST3#241]
Hi, i have angular projects, but my files have the vanilla Javascript icon
How can i tell Seti_UI that these files must have the Angular Icon ?

**Comment by ctf0** [comment]
the theme support angular by default, depends on the package u use and the scope it use
https://github.com/ctf0/Seti_ST3/blob/master/icons/Prefs/icon_angular.tmPreferences

**Comment by Tibicenas** [comment]
When you say package, do you mean what version of Seti_ST3 am i using ?

And i didn't understood about the scope sorry... i know about color syntax highlithing in the code thanks to scopeHunter but no about icons depending of the file :S

**Comment by Tibicenas** [comment]
Ok i checked now better
So every icons detect  source.[extension]   

Sass example 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist
  PUBLIC '-//Apple//DTD PLIST 1.0//EN'
  'http://www.apple.com/DTDs/PropertyList-1.0.dtd'>
<plist version="1.0">
    <dict>
        <key>scope</key>
        <string>source.scss</string>
        <key>settings</key>
        <dict>
            <key>icon</key>
            <string>file_type_scss</string>
        </dict>
    </dict>
</plist>
```

javascript example

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist
  PUBLIC '-//Apple//DTD PLIST 1.0//EN'
  'http://www.apple.com/DTDs/PropertyList-1.0.dtd'>
<plist version="1.0">
    <dict>
        <key>scope</key>
        <string>source.js</string>
        <key>settings</key>
        <dict>
            <key>icon</key>
            <string>file_type_js</string>
        </dict>
    </dict>
</plist>
```

but with angular the string is:  ` <string>text.html.basic.angularjs</string>`

And i don't know what is suppose to scope, because i have like 4 Angular apps and always show .js icon instead angular icon :S    Have this case a dependency packpage?

**Comment by ctf0** [comment]
what i mean about the package is something like https://github.com/angular-ui/AngularJS-sublime-package
and about the scope i mean https://github.com/angular-ui/AngularJS-sublime-package/blob/master/AngularJS.tmLanguage (check last line) and u can also get the scope name through scopehunter

**Comment by Tibicenas** [comment]
Mnn so meanwhile.... in case i always have files like the following: 

whatever.module.js
whatever.controller.js
whatever.factory.js
whatever.component.js
(there are more conventions, like .ctrl.js   .directive.js  etc.. )
can i add like more strings in the xml ? like the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist
  PUBLIC '-//Apple//DTD PLIST 1.0//EN'
  'http://www.apple.com/DTDs/PropertyList-1.0.dtd'>
<plist version="1.0">
    <dict>
        <key>scope</key>
        <string>source.module.js</string>
        <string>source.controller.js</string>
        <key>settings</key>
        <dict>
            <key>icon</key>
            <string>file_type_angular</string>
        </dict>
    </dict>
</plist>
```

**Comment by ctf0** [comment]
u can do so but this is bad for the long run
