### ISSUE TITLE
Jenkins Icons ( or for whatever NEW icon to add )

### ISSUE THREAD

**Issue by Tibicenas** [ctf0/Seti_ST3#242]
Hi, i love your UI and i setup for my Devops friendworker !
But there is no icon for Jenkinsfile, i would be glad to create the icon but i don't know how can i setup it to detect Jenkinsfile,

**Comment by ctf0** [comment]
check the included icon settings as an example, or send me the icons in 16x16 & 32x32 and the scope name for Jenkins lang and i will do it
