### ISSUE TITLE
It's messing with the syntax files

### ISSUE THREAD

**Issue by bfred-it** [ctf0/Seti_ST3#245]
For some reason it keeps overriding my preferences for the syntax. I select "SCSS" from the bottom right corner of ST (and also set it as default) but files keep being opened with Seti's own broken syntax files.

### Correct

<img width="237" alt="screen shot 2016-05-27 at 22 14 24" src="https://cloud.githubusercontent.com/assets/1402241/15612317/1e57ca58-23e3-11e6-9151-7d5bff923e8b.png">

### Broken (Seti)

<img width="240" alt="screen shot 2016-05-27 at 22 14 02" src="https://cloud.githubusercontent.com/assets/1402241/15612322/23d15daa-23e3-11e6-9368-ef4763217570.png">

**Comment by ctf0** [comment]
open `icons>Lang>SCSS' and change last lines to 
```
<key>scopeName</key>
<string>source.scss</string>
```
and tell me if its fixed or not.

**Comment by bfred-it** [comment]
Not fixed :/

**Comment by ctf0** [comment]
mmm, okay, i will delete them from the package.

**Comment by ctf0** [comment]
@bfred-it  are the icons still working as they should ?

**Comment by bfred-it** [comment]
Yep! I removed both SCSS and the SASS files to test it, restarted multiple times and opened new windows/folders. Looking good in ST3 b3114

<img width="69" alt="screen shot 2016-05-30 at 12 03 15" src="https://cloud.githubusercontent.com/assets/1402241/15640140/4c0d2760-25e9-11e6-9d71-1b02c212c637.png">

**Comment by ctf0** [comment]
have u cleard the cache ? also note that sass have different icon than scss, so have u test both ?
