### ISSUE TITLE
Seti_UI overlap other syntaxes and does not allow to make them default

### ISSUE THREAD

**Issue by BjornMelgaard** [ctf0/Seti_ST3#246]
```
# open file header.html.slim
>>> view.settings().get('syntax')
'Packages/Seti_UI/icons/Langs/Ruby Slim.tmLanguage'
# enable "open all as"
Assigning slim to syntax Packages/Ruby Slim/Syntaxes/Ruby Slim.tmLanguage
reloading settings Packages/User/Ruby Slim.sublime-settings
# open again
>>> view.settings().get('syntax')
'Packages/Seti_UI/icons/Langs/Ruby Slim.tmLanguage'
```

I already tried to reinstall `Seti_UI` and `Ruby Slim` packages

**Comment by BjornMelgaard** [comment]
solve this by deleting `Packages/Seti_UI/icons/Langs/Ruby Slim.tmLanguage`

**Comment by ctf0** [comment]
is the icons still working as they should ?

**Comment by BjornMelgaard** [comment]
Yes, before and after deletion
[`.config/sublime-text-3`](https://dropmefiles.com/RnnzJ) folder

**Comment by ctf0** [comment]
okay

**Comment by BjornMelgaard** [comment]
:smile:

**Comment by ctf0** [comment]
LOL, files will be removed in the next release

**Comment by BjornMelgaard** [comment]
Ah, lol, I thought that 'okay' mean 'problem not in Seti_ST3' and I decided not to bother you with my ignorance and forget it

**Comment by ctf0** [comment]
hahaha , no its okay, it will be fixed

**Comment by BjornMelgaard** [comment]
Don't remove `icons/Langs` dir, it break colorization, only `Ruby Slim.tmLanguage` incompatible with `Ruby Slim` package, I removed it

Also, I wand to ask you to add comment colorization to CoffeeScript, i.e

![28-21 53 02](https://cloud.githubusercontent.com/assets/7573215/15629310/93737bde-251e-11e6-9073-28e1e61c02e3.png)

**Comment by BjornMelgaard** [comment]
Lol, I just did it
icons/lang/coffeelang.tmlang
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>CoffeScript</string>
	<key>fileTypes</key>
	<array>
		<string>coffee</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.coffee</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)(?!\{).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.coffee</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js, source.coffee</string>
</dict>
</plist>
```

**Comment by ctf0** [comment]
the included lang files are only to make the icons show up, they are not to meant to be a an external lang files, however any additions u want to add, please add it to the scheme file it self and it will be picked up automatically.

also as i dont have coffeescript over here, try to remove its config files as well like u did with ruby and see if the icon still working or not.

**Comment by BjornMelgaard** [comment]
Hm, yes, with empty `Seti_UI/icons/Langs` folder icons don't work, I did not notice it first, because it affects to files, which don't have other plugins, like .gitignore

**Comment by ctf0** [comment]
so what now ?
