### ISSUE TITLE
Remove Gulpfile syntax

### ISSUE THREAD

**Issue by cyberwombat** [ctf0/Seti_ST3#249]
For some reason the theme has a syntax for Gulpfile which effectively prevents any javascript snippets/plugins from working since its no longer recognized as javascript by ST plugins. I keep removing it but every update readds it and there is no way that I can find to prevent it. Asking ST to open all files as JS doesnt work - reverts back as soon as the gulpfile is reopened. 

Is there any reason this is there?

Thanks

**Comment by ctf0** [comment]
i think i know why, can u send me a file with some code to test with ?

**Comment by cyberwombat** [comment]
It doesnt matter what's in it. I use plugins such as 'javascript-snippets' that for example let me type 'cl' and press enter and I will a console.log. Or I can select a group of text and hit Cmd-/ and it will comment things out. This works in a regular JS file but not once the GulpFile JS syntax is on.

**Comment by ctf0** [comment]
okay, i will look into it today

**Comment by Passerby** [comment]
Ruby Slim has the same problem

**Comment by ctf0** [comment]
@cyberwombat apply the last commit and see if its fixed.
@Passerby ruby slim is already removed , so ur ST package should handle that automatically.

**Comment by cyberwombat** [comment]
Looks like it works. Sweet. Thanks!
