### ISSUE TITLE
Is there a way to tweak the color of folder icon in sidebar?

### ISSUE THREAD

**Issue by larryzhao** [ctf0/Seti_ST3#250]
This is a really good scheme, just that I found the white folder icon is a little bit eyesore, so if there's a setting to tweak the color?

Best Regards.

**Comment by ctf0** [comment]
u r right, i will come up with something soon.

**Comment by ctf0** [comment]
done , check the last update.

**Comment by larryzhao** [comment]
@ctf0 Thanks a lot!

**Comment by larryzhao** [comment]
Hi, @ctf0 , just get back to this issue, but I didn't found any thing related to tweaking the folder icon's color/brightness in README@github.com / README@packagecontrol.io. 

Is it what I thought was wrong ? that the folder icon an icon pic that actually I could not tweak the color/brightness of it?

**Comment by ctf0** [comment]
no that wont be possible , because st theming is not dynamic, i will have to hard code the params into the theme which is not handy nor maintainability friendly at all.
