### ISSUE TITLE
Pug Icon

### ISSUE THREAD

**Issue by we-fix-it** [ctf0/Seti_ST3#251]
I notice, that the PUG files icon doesn't appear, do you think is on the list to next update?

**Comment by ctf0** [comment]
pug is jade i believe, right ? if so its already supported unless they have changed the scope

**Comment by we-fix-it** [comment]
Yes Jade is Pug, but the icon is not the same than Jade, so i only hope you can add the icon to the scope and all will be awsome, thanks.

**Comment by ctf0** [comment]
u can add the scope ur self and send me a PR 👍

**Comment by we-fix-it** [comment]
ok, i will try, idk how but im searching, thanks.
