### ISSUE TITLE
Separate Syntax Definitions from Theme

### ISSUE THREAD

**Issue by fnky** [ctf0/Seti_ST3#252]
I propose that we separate all syntax definitions to their own packages. There's a lot of issues with the current stance, which has already been mentioned a few times (_see #97 and #245_). Some of the benefits of this change would:

* Keeps updates and the project focused on the theme and not syntax.
* Be easier to maintain both in a development standpoint, but also regarding support.
* Avoid conflicts with other packages, which might be far superior. Seti seems to take over syntax definitions with the same name, which is not ideal.
* Let people choose their syntax as a lot of the syntax definitions aren't even necessary; such as `Gulpfile`/`Gruntfile`, `LICENSE`, `NPM JSON`/`Bower JSON`, etc.

The only contra is that you won't have an icon for filetypes that you don't have syntax definitions for, but that to me isn't really a contra, as it wouldn't even matter if I had icon support for filetypes that I don't even use.

My current issue is that it conflicts with the official Rust package, which provides a far superior syntax definition for its own language, and Seti seems to take over other syntax files, that I don't need it to.

I really hope you consider this change.

**Comment by ctf0** [comment]
i understand ur point of view but sadly this wont be doable, however rust support was added along ago and i belive ur package is not working because of the scope name in the syntax file came with seti so try to delete that syntax file from the theme and clear the cache and see if the icon still working, if yes then i will delete the file and push a new update.

**Comment by fnky** [comment]
The thing is, whenever I then update I have to manually go and delete the unnecessary files. I'd rather provide my own syntax definitions for the languages that I know I am going to use, and not anything else. 

Perhaps leave special file definitions like `Gulpfile`, `NPM JSON`, etc. unless they conflict for those kind of icons to work. But syntax definitions for Rust, Less, Stylus, etc. shouldn't be mandatory, as the icons would work fine if I got definitions from another package.

**Comment by ctf0** [comment]
actually if u deleted them and the icon is still working then i would remove it from the theme aswell, the thing is that those files are only there so sublime can display the icons for various files **NOT** to replace the original definition of the syntax

**Comment by fnky** [comment]
So I propose we delete the syntax definitions that already has packages for those languages, like:

```
Less
Handlebars
Julia
CoffeeScript
Mustache
Stylus
Swift
Rust
```

**Comment by ctf0** [comment]
am positively sure that if i deleted the LESS , you will get the icon of the css instead, have u tested them all > cleared the cache and got them all working ?

**Comment by fnky** [comment]
I'll test it out :-)

**Comment by fnky** [comment]
Seems to work. All the major languages are from other packages, that provides syntax definitions based on filetypes and scope.

![image](https://cloud.githubusercontent.com/assets/995050/16260079/fa66e498-3865-11e6-8f9a-9b6fb352118c.png)

Now the only hiccups I found was that some files got wrong icons:

- SVG — `.svg` -> `markup`
- Julia — `.jl` -> `source`
- Sass — `.sass` -> `HAML`

I for Julia and Sass I used their corresponding packages `Julia` and `Sass` (while having `SCSS` for `.scss` files)

**Comment by ctf0** [comment]
are u sure that u cleared the cache after removing the config files from seti ?, if yes then we will delete the previously mentioned but leave the ones with wrong icons, k ?

**Comment by fnky** [comment]
Yes.

**Comment by ctf0** [comment]
sass & scss were removed because ppl kept having issues with them for some reason so i removed em along ago, anyway delete those that not needed and send me the PR.
