### ISSUE TITLE
Keeps setting Handlebars files to Mustache

### ISSUE THREAD

**Issue by Craicerjack** [ctf0/Seti_ST3#253]
As the description says. Seti keeps changing my handlebars files to Mustache when I want them as Handlebars. I had removed the Mustache related files to stop this happening but in the latest update they were reinstalled. 
Simply removing the `.hbrs` extension from the Mustache file didnt work.

**Comment by ctf0** [comment]
oh, i just found that i wrote the name wrongly, get the last push and try again, clear the cache afterword.
