### ISSUE TITLE
Sass highlighting doesn't work properly

### ISSUE THREAD

**Issue by DCzajkowski** [ctf0/Seti_ST3#254]
### Introduction
Hi,
I use Seti_UI only for sidebar icons. In the meanwhile I use Material theme. Recently I started working with `.sass` files. The code highlighting was all messed up. I remember I have installed a `Sass` plugin and it worked, but apparently it doesn't anymore.

### Problem
When I clicked in the bottom right corner I got a list of languages. What appears is, that I don't have a `Sass` selected, but `User > Sass`. Changing default language doesn't help. After removing Seti_UI the code highlingting works as it should.

### Question
I raised this issue because it is clearly Seti_UI's fault that it overrides color highlighting files with its own ones. How do I overcome this?

### Screenshots
With Seti UI enabled:

![](http://dczajkowski.com/projects/Codecourse/seti/incorrect.png)

---

With Seti UI disabled:

![](http://dczajkowski.com/projects/Codecourse/seti/correct.png)

---

With Seti UI enabled. Incorrect code highlighting file selected:

![](http://dczajkowski.com/projects/Codecourse/seti/selected.png)

**Comment by ctf0** [comment]
actually both sass & scss files were removed from Seti along ago because of issues like this, so i think u should update to the latest and clear the cache

**Comment by DCzajkowski** [comment]
Weird. After disabling Seti_UI correct highlighting appeared. After removing it entirely it didn't.
I cleared the `Cache` folder in Sublime, but the `User > styles` still appear...
I removed all Seti_UI folders I could find, but it is still there.

Do you know how to clear cache or preview where those files come from?

**Comment by ctf0** [comment]
material also have the icon support because its based on seti , so removing seti  wont cuz the icons to disappear, remove any theme that have icons support and u will get the default icons back

**Comment by DCzajkowski** [comment]
No, I mean some icons that are not in the Material theme still are there. Rebooting my computer right now to investigate it further.

**Comment by DCzajkowski** [comment]
Ok, so after long research this is what I found:
```
view.settings().get('syntax')
```
This pasted into console with a sass file opened returned me:
```
'Packages/User/Themes/Seti_UI/Langs/Sass.tmLanguage'
```

Even though I removed the Seti_UI package using Package Control it still is there.

After removing the Seti_UI folder I got an error when opening `.sass` file, that `Packages/User/Themes/Seti_UI/Langs/Sass.tmLanguage` could not be found.

Even though I removed the extension the folder is still there and Sublime still points to it. Changing `open all with current extension as` doesn't help, because it gets overriden :/

**Comment by DCzajkowski** [comment]
Ok, it actually looks like this is Material Theme's fault of wrongly mapping extensions with their syntax files.

This thread is gold: https://forum.sublimetext.com/t/solved-view-syntax-open-all-with-current-extension-as-scss/18129/5

Issue on Material Theme repo: https://github.com/equinusocio/material-theme/issues/682

---

I guess, that if updating Material Theme didn't help, I will have to reinstall Sublime entirely.

Ehh. Thanks for your support!
