### ISSUE TITLE
Handlebars Syntax Highlighting Breaks With Seti

### ISSUE THREAD

**Issue by matthoiland** [ctf0/Seti_ST3#256]
Simply having Seti UI installed in ST3 breaks all `handlebars` syntax highlighting. 

I've many color schemes with the same result. The example below is using `Monokai Extended`. I also have the `handlebars` package installed.

Removing the Seti UI package resolves the issue.

Any ideas?

![without](http://hoidrop.s3-us-west-2.amazonaws.com/without.png)
![with](http://hoidrop.s3-us-west-2.amazonaws.com/with.png)

**Comment by ctf0** [comment]
just remove the handlebars files from `icon/Lang` & `icon/Prefs` , clear the cache and see if the icon still shows up
