### ISSUE TITLE
Theme breaks update status dialog box

### ISSUE THREAD

**Issue by jeffschwartz** [ctf0/Seti_ST3#258]
When selecting `Check for Updates...` the resulting dialog box is corrupted as per image below:
![screen shot 2016-07-08 at 6 53 39 am](https://cloud.githubusercontent.com/assets/271288/16685390/dc76befc-44d8-11e6-97c0-6e20d41109ac.png)

When restoring original Sublime theme and then selecting `Check for Updates...` the resulting dialog box is no longer corrupted as per image below:
![screen shot 2016-07-08 at 6 56 55 am](https://cloud.githubusercontent.com/assets/271288/16685458/3a87290a-44d9-11e6-922c-206a7ac69175.png)

Sublime Text 3 Dev Channel, Build 3118
Mac OS X 10.9.5

**Comment by ctf0** [comment]
here is mine
![screen shot 2016-07-08 at 9 02 03 pm](https://cloud.githubusercontent.com/assets/7388088/16698590/547ded1e-454f-11e6-8e7f-bed46989f714.png)

same st build, Osx 10.11.5

**Comment by jeffschwartz** [comment]
@ctf0 our Mac OS X versions differ.

**Comment by ctf0** [comment]
this is related to the osx not the theme :(

**Comment by jeffschwartz** [comment]
@ctf0 to test your assumption that it is my OS X version I installed a different theme. We can agree that if it is my OS X version then all themes running on my machine should also break. However that is not the case; I installed the [Soda Theme] ( https://github.com/buymeasoda/soda-theme) and as evidenced by the following image it works flawlessly :

![screen shot 2016-07-13 at 9 31 40 am](https://cloud.githubusercontent.com/assets/271288/16805200/12ad1144-48dd-11e6-8eb5-bb3fba55e345.png)

**Comment by jeffschwartz** [comment]
@ctf0 and when I switch to the light version of the Soda theme it also works:

![screen shot 2016-07-13 at 9 46 38 am](https://cloud.githubusercontent.com/assets/271288/16805597/eb00bf2c-48de-11e6-8a57-c10fb523954f.png)

**Comment by ctf0** [comment]
i understand but when i firstly created seti i was on the same osx version as u and it was an issue with the font color which got changed so u can read the text in console, then days passed and i installed the new version of osx and magically the problem is no longer showing up, 

i cant remember exactly what settings to change /edit to even debug this problem, sadly all i can advice u with atm is to use any other theme instead of seti.

**Comment by jeffschwartz** [comment]
@ctf0 do you think it might help you to look at the Soda theme? Maybe you can spot the setting it is using and add it to Set.

**Comment by ctf0** [comment]
am super busy atm but will try later.

**Comment by hsiktas** [comment]
I use this theme on both macOS 10.12 and Windows 10 and the issue is present on both operating systems.
These are my settings for the theme:

"Seti_SB_orange": true,
"Seti_accent_red": true,
"Seti_orange_button": true,
"theme": "Seti.sublime-theme",
