### ISSUE TITLE
Fails to load syntax for .hbs files on open with the Handlebars package installed

### ISSUE THREAD

**Issue by TylerJBrown192** [ctf0/Seti_ST3#260]
As stated in the title, Seti_UI somehow conflicts with the Handlebars package. Interestingly, this only occurs for the .hbs file extension, but not .handlebars.

See Handlebars package [issue here](https://github.com/daaain/Handlebars/issues/87) for more detail.

**Comment by TylerJBrown192** [comment]
In the version notes [here](https://github.com/ctf0/Seti_ST3/blob/145030a97d8a1c71384efb0f327227c17395cfbb/messages/1.11.3.txt) it states that 'handlebars are now supported', yet I don't quite see what's fully being supported or applied to the syntax in the screenshot below. This is a pure install of Sublime Text 3 with only Package Control and Seti_UI installed. I also installed ApplySyntax as stated in the installation text to see if that would improve anything, but it didn't.

![screen shot 2016-08-04 at 6 39 18 pm](https://cloud.githubusercontent.com/assets/10467121/17423814/cc694782-5a72-11e6-85d5-17d0f18f0114.png)

I love this UI package and would really enjoy continuing to using it. I'm going to submit a PR removing all references to Handlebars syntax settings in favor of @daaain 's Handlebars package.

**Comment by ctf0** [comment]
seti by all definition doesnt support any language highlight , the support is only for the icons the shows up in the sidebar, which means that ofcourse u will need to install the syntax package for what ever lang u r going to use

**Comment by ctf0** [comment]
i have seen the issue on HB and i would recommend is u install ST,HB then seti, remove the hbs pref from seti > clear the cache > try again, now everything should work as it should but not sure if the icons will show up or not.

**Comment by TylerJBrown192** [comment]
Thank you for the response @ctf0 . 

I'm not entirely sure how I would 'remove the hbs pref from Seti'. I have no experience creating or modifying packages in Sublime, so I'm just giving a few things a try right now. 

I deleted the file Seti_UI/icons/Langs/Handlebars.tmLanguage and that seemed to resolve the issue: There are no errors thrown by Sublime / the Seti_UI package in a popup or in the console, the Handlebars package properly applies it's syntax, and the icon still shows up. Would this be an okay solution to create a pull request for?

**Comment by ctf0** [comment]
thanx for the PR
