### ISSUE TITLE
How to limit to sidebar only? 

### ISSUE THREAD

**Issue by jaepage** [ctf0/Seti_ST3#264]
I only want a dark sidebar and branded sidebar icons. The other changes are too far-reaching (especially the loss of color in tabs, scrollbars, and search fields). 

Is it possible to limit this package to the sidebar only, please? 

Sublime Text 3, build 3114.
Mac OS 10.11.6 (El Capitan).

**Comment by ctf0** [comment]
nop but u can fork it and make ur own version.

**Comment by jaepage** [comment]
Do you know if I can simply drop your icons folder somewhere and have Sublime use them, or would I need to direct Sublime to the folder somehow? Putting the icons folder into `~/Libary/Application Support/Sublime Text 3/Packages/User/` kills the default icons, but doesn't use the new icons. Thank you.
