### ISSUE TITLE
By default top heading does not shows in v.14

### ISSUE THREAD

**Issue by seth2810** [ctf0/Seti_ST3#265]
New version of theme require that one of the settings Seti_top_heading_* muse be enabled otherwise heading does not visible.

**Comment by seth2810** [comment]
Maybe better to do the top_heading component optional?

**Comment by ctf0** [comment]
am sorry, what heading ? can u show me a screenshot ?

**Comment by ctf0** [comment]
fixed, plz manually install the latest commit

**Comment by seth2810** [comment]
I talk about this 
![screenshot at 2016-08-27 01 25 16](https://cloud.githubusercontent.com/assets/845078/18022231/c97b6fde-6bf5-11e6-9cf9-04639b2714cd.png). Same problem inside https://github.com/ctf0/Seti_ST3/issues/268

**Comment by mucill** [comment]
+1 for the same Issue. Any solution ?
