### ISSUE TITLE
Close tab buttons broken with latest update (v14.0.0)

### ISSUE THREAD

**Issue by Effenberg0x0** [ctf0/Seti_ST3#266]
All tabs now have broken close buttons. Please see the attached screenshot. 
![screenshot from 2016-08-26 09-30-52](https://cloud.githubusercontent.com/assets/4016782/18005376/fb86b686-6b6f-11e6-9fec-232f6c74d3a9.png)

**Comment by ctf0** [comment]
uninstall it , clear the cache and reinstall the theme again

here is what i have
![untitled](https://cloud.githubusercontent.com/assets/7388088/18012190/be479b2a-6bb8-11e6-81ac-2f55d99ff259.jpg)

**Comment by Effenberg0x0** [comment]
Yep, it was a cache problem, that's embarrassing. Thanks.

**Comment by ctf0** [comment]
np glad its fixed now :)
