### ISSUE TITLE
Something error after update SetiUI package

### ISSUE THREAD

**Issue by hansnataniel** [ctf0/Seti_ST3#267]
After SetiUI plugin updated, now everytime I open my ST3, I get an error message like this:

Error loading syntax file
"Packages/Seti_UI/Widgets/console.sublime-syntax": Error parsing plist
xml: expected<in file
Packages/Seti_UI/Widgets/console.sublime-syntax on line: 1

**Comment by ctf0** [comment]
have u cleared the cache ?

**Comment by hansnataniel** [comment]
Sorry, how can I clear the cache for the ST? my ST is build 3083.

**Comment by ctf0** [comment]
thats why, u need to update ur st build , current stable is 3114
about clearing the cache `found right next to the packages folder`
