### ISSUE TITLE
Seti Orig sidebar layout problem

### ISSUE THREAD

**Issue by kgizdov** [ctf0/Seti_ST3#268]
Since the last update, I have this bug
![seti_orig](https://cloud.githubusercontent.com/assets/3164953/18018530/cb9e7982-6bd7-11e6-9284-e349bf05a359.png)
Switching back to Seti corrects the issue, but Seti_orig, which is my preferred theme suffers from this issue.

**Comment by simov** [comment]
When I finally restarted Sublime:
![sidebar](https://cloud.githubusercontent.com/assets/1694112/18067682/7dc3181e-6e46-11e6-9ca1-6c5584f18011.png)

**Comment by ctf0** [comment]
https://github.com/ctf0/Seti_ST3/issues/265
