### ISSUE TITLE
Broke Sidebar support, mixed Theme Usage

### ISSUE THREAD

**Issue by jmConan** [ctf0/Seti_ST3#269]
Hi, 
I'm running Linux with Build 3114.

Last nights updated pretty much broke the whole theme.

Already removed Seti_UI & Seti_UX and reinstalled. No fix there.

No Icons, no mods on the sidebar, tab selection and even regular tabs are now in some kind of mixed theme interpretation.

![screenshot_2016-08-27_10-43-16](https://cloud.githubusercontent.com/assets/3360825/18026330/1b2f611c-6c43-11e6-9239-cc3aac2ee3e6.png)

**Comment by ctf0** [comment]
clean the cache as some changes made to the folder structure.

**Comment by jmConan** [comment]
the patch last night fixed it ;)

**Comment by ctf0** [comment]
great :)
