### ISSUE TITLE
Sidebar Positioning

### ISSUE THREAD

**Issue by jaegz** [ctf0/Seti_ST3#271]
It looks like an update recently came in, as I had to redeclare the theme as Seti in my user preferences. Now the sidebar top position / padding is larger than usual. I didn't see it in the docs, but is there an option to pull the folder list up?

![image](https://cloud.githubusercontent.com/assets/7094801/18132695/ca3df04a-6f65-11e6-8398-4f2a96e6a0ce.png)

Current settings
```
{
	"Seti_sb_small_padding": true,
	"Seti_sb_tree_small": true,
	"Seti_tabs_small" : true,
	"caret_extra_bottom": 3,
	"caret_extra_top": 3,
	"caret_extra_width": 2,
	"color_scheme": "Packages/User/SublimeLinter/Blackboard (SL).tmTheme",
	"font_face": "Consolas",
	"font_size": 9,
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"overlay_scroll_bars": "enabled",
	"theme": "Seti_orig.sublime-theme"
}
```

**Comment by ctf0** [comment]
https://github.com/ctf0/Seti_ST3/issues/265 , already fixed

**Comment by jaegz** [comment]
my bad on the duplicate - thanks for the heads up @ctf0 !
