### ISSUE TITLE
My icons have significantly shrunken since the last update.

### ISSUE THREAD

**Issue by juanrgon** [ctf0/Seti_ST3#272]
<img width="259" alt="screen shot 2016-09-11 at 3 10 29 pm" src="https://cloud.githubusercontent.com/assets/17055383/18419839/eed13f8c-7831-11e6-8aa2-4ba696092568.PNG">

**Comment by ctf0** [comment]
clear the cache and try again, but all i did was making the normal = the @2x dim

**Comment by juanrgon** [comment]
I'm on a Mac.


I quit Sublime, removed the `Cache` folder next to `Packages`, and reopened Sublime, but I still had small icons after that. 

I decided to try quitting sublime and removing one of the **2x** dimensions, `file_type_git@2x.png`

Before: 

<img width="264" alt="screen shot 2016-09-11 at 5 49 06 pm" src="https://cloud.githubusercontent.com/assets/17055383/18420766/61c023c6-7848-11e6-9d1c-6f20bb71c87b.PNG">

After:

<img width="257" alt="screen shot 2016-09-11 at 5 50 34 pm" src="https://cloud.githubusercontent.com/assets/17055383/18420767/649a6322-7848-11e6-908b-cdb9ca0b1ee5.PNG">

So, you're right; It seems like all you did was add 2x versions of each icon, but this seems to be *why* the icons are smaller. 

It seems like the 2x versions of each icon is the exact same in terms of memory size. For instance, `file_type_git.png` and `file_type_git@2x.png` are both 15kb in size.

**Comment by ctf0** [comment]
this is kinda weird because am also on mac and all is good, even on windows all is working as expected.

**Comment by juanrgon** [comment]
😨

**Comment by ctf0** [comment]
@juanrgon any update on this yet ?

**Comment by cyy0418** [comment]
### How to solve?

**Comment by juanrgon** [comment]
I'm using a retina mac. 

I'm still not sure what the actual cause of the error is, but as a workaround, I've moved the @2x icons so that they won't be used by Sublime. 

For other mac users:

```bash
> cd '~/Library/Application Support/Sublime Text 3/Packages/Seti_UI/icons'
> mkdir ~/icons_cache
> mv *2x.png ~/icons_cache/
```

**Comment by ctf0** [comment]
@juanrgon so the normal works correctly for u ? 

the reason i asked is that ST will convert the normal images dim to 16*16 and as the 2x is the same as the normal so he use the 16*16 for the retina as well ,if u have a normal non-retina display u wouldnt have any issues.

**Comment by juanrgon** [comment]
@ctf0 Shouldn't the `2x` be twice as large as the normal icons, i.e., `32*32`? My understanding is that the `2x` icons are halved in size on retina displays?

**Comment by ctf0** [comment]
what happend is ST read the icons and found that the normal is the sam dim the 2x so it went with the normal instead which gets resized into `16*16`

**Comment by juanrgon** [comment]
Resizing the @2x to 64*64 resolves the issue.

**Comment by ctf0** [comment]
my theory was right then, i will fix that in that next commit.

**Comment by NekR** [comment]
So fixed or what?

**Comment by NekR** [comment]
@juanrgon
> For other mac users:

Just tried this fix -- doesn't work for me on MBPr :-(

**Comment by ctf0** [comment]
i will push the fix today

**Comment by NekR** [comment]
I didn't mean to pressure or something. Thanks for your work!

**Comment by juanrgon** [comment]
@NekR Did you close and reopen sublime afterwards?

**Comment by NekR** [comment]
@juanrgon of course :-)

**Comment by iamocean** [comment]
![](https://cloud.githubusercontent.com/assets/1709810/19186844/c7298cf8-8cba-11e6-9d49-1d70064052ad.jpg)

@ctf0 

1. i have updated to new version, and the icons is still display error.
2. npm icon size is 16x16, but display is correct.

**Comment by ctf0** [comment]
fixed once and for all in the last release.
