### ISSUE TITLE
Coffeescript highlighting is broken since last upd

### ISSUE THREAD

**Issue by Reaverart** [ctf0/Seti_ST3#273]
I'm used better coffeescript highlightning, but since last theme upd it switches to SETI_UI/coffeescritpt by default. "Open all with current extension" menu wont affect now, it resets to SETI_UI/coffeescritpt for each new opened file. Looks like with new release theme does override somewhere, had to manually switch syntax for each file now.

**Comment by ctf0** [comment]
my bad, i will remove the file , plz manually download the last commit and see if it fix ur issue

**Comment by Reaverart** [comment]
Yep, thanks, it works!

**Comment by ctf0** [comment]
i will update the theme with that then.
