### ISSUE TITLE
Sidebar icons for files (not folders) are super small after upgrading to 15.1.0

### ISSUE THREAD

**Issue by kylebebak** [ctf0/Seti_ST3#275]
This hadn't happened before. I was looking around `Seti.sublime-theme` to see if I could find where icon sizes are defined, but had no luck. Here's what I mean.

<img width="137" alt="screen shot 2016-09-15 at 10 31 23 am" src="https://cloud.githubusercontent.com/assets/1524088/18556005/9a840dc8-7b2f-11e6-9b85-35889208d2c2.png">

**Comment by ctf0** [comment]
check here https://github.com/ctf0/Seti_ST3/issues/272, i will fix asap

**Comment by kylebebak** [comment]
@ctf0 

Understood man, thanks for the explanation, and thanks for the killer theme =)
