### ISSUE TITLE
.yml icon is looking weird since the last icons update

### ISSUE THREAD

**Issue by simov** [ctf0/Seti_ST3#276]
![yml](https://cloud.githubusercontent.com/assets/1694112/18578003/15fd2ba8-7bf6-11e6-8a16-214bc4a7c8a5.png)

No idea if that's the new normal or something got messed up on my end, but it was a yellow icon saying yml before that.

**Comment by ctf0** [comment]
yes it was changed yes, https://github.com/ctf0/Seti_ST3/releases/tag/v15.1.0

**Comment by simov** [comment]
Ok, probably there is an issue/pr about it, but how is purple exclamation mark supposed to represent .yml files? I'm probably missing some logo or something.

**Comment by ctf0** [comment]
non of that, its just better than the old yellow squished icon.

**Comment by simov** [comment]
Ok, that makes sense, but not the exclamation mark :) I think some icon that relates more closely to a configuration file would be a better match.

**Comment by ctf0** [comment]
if u have a better one, either make and send me the PR or send me the icon directly
