### ISSUE TITLE
Syntax and Icon React JSX on Javascript (Babel) syntax

### ISSUE THREAD

**Issue by infantito** [ctf0/Seti_ST3#278]
Well, I want to use the syntax of Javascript (Babel) in files JSX (REACT); but changing the syntax the icon changes to JS; but I want this to stay with the icon react.

Because the tags (</>) in JSX no color and is not as similar to the syntax of Javascript (Babel)

app.js => icon_js => javascript (babel)
app.jsx => icon_jsx => javascript (babel)

**Comment by ctf0** [comment]
this is totally handled by the syntax it self not by the theme, but i can put back an explicit config for react `jsx files` and see if it works for u

**Comment by ctf0** [comment]
@infantito download the latest commit and see if it works as u expect or not.

**Comment by infantito** [comment]
I downloaded the entire project again and the js_icon still remains.
![javascript babel](https://cloud.githubusercontent.com/assets/9045302/18839526/ea922dfa-83d0-11e6-94fe-741b1fc673d8.PNG)
![react jsx](https://cloud.githubusercontent.com/assets/9045302/18839528/ea9b2a9a-83d0-11e6-9dce-ef5a60800135.PNG)

**Comment by ctf0** [comment]
okay, install scope hunter and tell me the scope for the file b4 and after using babel

**Comment by infantito** [comment]
Scope:                     source.js
                               meta.group.braces.curly.js
                               meta.group.braces.round.js
                               meta.jsx.js
                               meta.tag.jsx
                               entity.name.tag.jsx
------

![image](https://cloud.githubusercontent.com/assets/9045302/18841064/29c107da-83d6-11e6-8d44-134e41b5a362.png)

**Comment by ctf0** [comment]
okay, when u first open ST u the jsx should open with `React JSX` which is under `Seti_UI` option in the syntax list, if ur default syntax for js is babel , u should get everything without changing the syntax, does this many any sense ?

**Comment by infantito** [comment]
Well, I have to do every time I open sublime text?
That is tedious! :'(

**Comment by ctf0** [comment]
ofcourse not, the file should be picked up automatically on `React JSX` under seti when u open ST, same as gulpfile.js or any of the custom ones 👍

**Comment by infantito** [comment]
1. I define the syntax JSX file to react JSX
2. Close ST
3. Open ST and all my files .jsx should be painted as the syntax of javascript (babel)

=> But; the 3 does not work. :'(

**Comment by ctf0** [comment]
have i disabled the default js and make babel the default for all js files ?

**Comment by infantito** [comment]
what's your email address?
Or I paste the code here?

**Comment by ctf0** [comment]
u can paste it here, just small part to test with and the packages u use

**Comment by infantito** [comment]
Cambia la extensión a jsx.

Plugins ST:
1. Seti_UI (Origin)
2. Oceanic Next Color Scheme
3. Babel
4. Set syntax Javascript (Babel) => (Open all will current extension as...

Test: Try with javascript (babel) syntax and React jsx syntax; because the ui is different.

no more. :(

CODE:

'use strict';

var React = window.React,
    Router = window.ReactRouter,
    joinPath = require('./joinPath'),
    Route = Router.Route,
    DefaultRoute = Router.DefaultRoute,
    NotFoundRoute = Router.NotFoundRoute;

module.exports = function(path) {
  var mountPath;

  mountPath = path == null ? '/' : path;

  return (
    <Route path={mountPath} handler={Router.RouteHandler}>
      <Route path={mountPath} handler={login} />
      <Route path={joinPath(mountPath, 'changePassword/:token')} handler={recover} />
      <Route path={joinPath(mountPath, 'services')} handler={services} />
      <Route path={joinPath(mountPath, 'reports')} handler={reports} />
      <NotFoundRoute handler={notFound} />
    </Route>
  );
};

**Comment by infantito** [comment]
Cambia la extensión a jsx.

Plugins ST:
1. Seti_UI (Origin)
2. Oceanic Next Color Scheme
3. Babel
4. Set syntax Javascript (Babel) => (Open all will current extension as...

Test: Try with javascript (babel) syntax and React jsx syntax; because the ui is different.

no more. :(

CODE:

'use strict';

var React = window.React,
    Router = window.ReactRouter,
    joinPath = require('./joinPath'),
    Route = Router.Route,
    DefaultRoute = Router.DefaultRoute,
    NotFoundRoute = Router.NotFoundRoute;

module.exports = function(path) {
  var mountPath;

  mountPath = path == null ? '/' : path;
/*
  return (
    <Route path={mountPath} handler={Router.RouteHandler}>
      <Route path={mountPath} handler={login} />
      <Route path={joinPath(mountPath, 'changePassword/:token')} handler={recover} />
      <Route path={joinPath(mountPath, 'services')} handler={services} />
      <Route path={joinPath(mountPath, 'reports')} handler={reports} />
      <NotFoundRoute handler={notFound} />
    </Route>
  );/*
};

**Comment by ctf0** [comment]
okay i will test it later today and see what i get :+1:

**Comment by infantito** [comment]
Cambia la extensión a jsx.

Plugins ST:
1. Seti_UI (Origin)
2. Oceanic Next Color Scheme
3. Babel
4. Set syntax Javascript (Babel) => (Open all will current extension as...

Test: Try with javascript (babel) syntax and React jsx syntax; because the ui is different.

no more. :(

CODE: (Change extensión to .jsx)

[app.txt](https://github.com/ctf0/Seti_ST3/files/493779/app.txt)

**Comment by ctf0** [comment]
okay, i fixed it now, just make SUUUURE that u disable the default javascript package that comes with ST, download the latest commit and check for ur self, it will now be used under bable by default and u will have the react icon.
