### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by yoanmalie** [ctf0/Seti_ST3#279]
Hi,
Today, after a theme update, i have these two errors:

![image](https://cloud.githubusercontent.com/assets/3357171/18913174/aabf987c-8586-11e6-9bbc-4a471708ce6b.png)

Sublime Text 3, Build 3126

BTW, all the time after an update, i need to re edit my setting to change `"theme": "Default.sublime-theme"` to `"theme": "Seti.sublime-theme"`. Is that normal ?

**Comment by ctf0** [comment]
nop, the new ST un-load the theme and re-load it automatically after its downloaded,

for that issue, clear the cache folder and u are good to go 🍺
