### ISSUE TITLE
Some options are missing now

### ISSUE THREAD

**Issue by NekR** [ctf0/Seti_ST3#280]
Options such as `Seti_orange_button` and `Seti_orange_label` are missing now. I cannot find any changelog about it. What happened?

**Comment by ctf0** [comment]
they are removed in favour of the new accents flavored both for label and tab close

**Comment by NekR** [comment]
That's great, but nothing of that works only for "unsaved tabs", even things from this section: "// tabs unsaved bar ("Seti_accent_*": false)".

How I can make a tab with unsaved changes stand from all other tabs?

**Comment by NekR** [comment]
Oh, I see how it works now. Nevermind, sorry for disturbance.
