### ISSUE TITLE
always show the error message: "Error trying to parse sublime-syntax: %YAML indicator is required in Packages/Seti_UI/Widgets/console.sublime-syntax:1:1"

### ISSUE THREAD

**Issue by fhefh2015** [ctf0/Seti_ST3#281]
`Error loading syntax file "Packages/Seti_UI/Widgets/console.sublime-syntax": Error trying to parse sublime-syntax: %YAML indicator is required in Packages/Seti_UI/Widgets/console.sublime-syntax:1:1`

**Comment by fhefh2015** [comment]
i reinstall sublime text 3 and reinstall seti_ui.
it works ok.

**Comment by ctf0** [comment]
sweet :+1:
