### ISSUE TITLE
Wrong icons?

### ISSUE THREAD

**Issue by kgizdov** [ctf0/Seti_ST3#282]
I think I'm having the wrong icons for certain extensions
![makefile_icon](https://cloud.githubusercontent.com/assets/3164953/19083817/c48ff2f4-8a5b-11e6-81fb-661a1c8584ca.png)
![xml_icon](https://cloud.githubusercontent.com/assets/3164953/19083820/c8597dd8-8a5b-11e6-82f6-c6ff2c96dccf.png)

**Comment by ctf0** [comment]
i think those are the correct ones, what are u expecting ?

**Comment by kgizdov** [comment]
If you Google 'XML icon' you can see </> everywhere, because XML is a markup (tagged) language. Makefiles are not markup and do not have tags in them. They are their own GNU-make syntax. I used to get the cog icon before for them and I used to the the </> for XML. Now they different/swapped for some reason, but are not correct.

**Comment by ctf0** [comment]
the icon for makefile is the source icon, which by default ST assign to many syntax, but i think it makes more sense to swap them both i guess

**Comment by ctf0** [comment]
update:

i dont have control over either of those icons, its to the syntax u chose to open those files.
