### ISSUE TITLE
Files with .cfc and .cfm extension have wrong icons

### ISSUE THREAD

**Issue by kismann** [ctf0/Seti_ST3#285]
OS: Windows 10
ST 3, Build 3126

ColdFusion files with *.cfc or *.cfm extension have wrong icons.

![image](https://cloud.githubusercontent.com/assets/10376544/20328174/5b1c4924-ab91-11e6-9c9d-4c344fdc0f81.png)

But \Sublime Text 3\Packages\Seti_UI\icons Directory have correct icons:
![image](https://cloud.githubusercontent.com/assets/10376544/20328230/ae8c270a-ab91-11e6-91c6-2483653a4f83.png)

![image](https://cloud.githubusercontent.com/assets/10376544/20328259/e16ca280-ab91-11e6-959a-3554605de843.png)

**Comment by ctf0** [comment]
which package r u using ?

**Comment by kismann** [comment]
@ctf0 CFML package for ST3
https://github.com/jcberquist/sublimetext-cfml

**Comment by ctf0** [comment]
oh, the scope has changed, can u edit it and send me a PR or should i do it ?

**Comment by ctf0** [comment]
download the last commit manually and see if it fix ur issue

**Comment by kismann** [comment]
@ctf0 thx, it works with both packages.
https://github.com/jcberquist/sublimetext-cfml and https://github.com/SublimeText/ColdFusion
