### ISSUE TITLE
Add JADE icons

### ISSUE THREAD

**Issue by khex** [ctf0/Seti_ST3#286]
![file_type_jade](https://cloud.githubusercontent.com/assets/7450904/20648541/a7ccd534-b4b2-11e6-913d-5ce7292128e4.png)
![file_type_jade 2x](https://cloud.githubusercontent.com/assets/7450904/20648542/a7ce7d9e-b4b2-11e6-92a9-118fa99df4ab.png)

**Comment by ctf0** [comment]
jade or pug is already added, however if u prefer another, just send me a PR 😉
