### ISSUE TITLE
Removing padding from Quick Panel

### ISSUE THREAD

**Issue by Mike-NetCode** [ctf0/Seti_ST3#287]
If I understand correctly, the `Seti_panel_nrml` setting should remove the large padding in Quick Panel/View and make it closer to the original Sublime Text line spacing which is quite small.

However after enabling this option there's no difference in the Quick Panel and I still have limited vision of items in there. How can I make the padding as little as possible so that I see more items on the list?

![](http://i.imgur.com/pXibBRM.png)

**Comment by ctf0** [comment]
here is the current look
![demo](https://cloud.githubusercontent.com/assets/7388088/20649954/c0d9f20c-b4d3-11e6-82ca-2a3cf2ac15de.jpg)

and what i believe u want is to remove the whole padding of the items, for that u can add a new option with the settings u want and send me a PR

**Comment by Mike-NetCode** [comment]
Oh I see now what this option is for. Yes, correct, I would like to remove the top/bottom padding of the items. I see if I can do it properly. Thanks!
