### ISSUE TITLE
Dark fold button setting

### ISSUE THREAD

**Issue by arturoSoto** [ctf0/Seti_ST3#290]
Hello!
Today i installed your extension and is very pretty.
But i have a suggestion:
Can you add an entry in Seti.sublime-theme file that allow change fold button color from user settings file in next version?
I already add a entry like this if it can be useful:
```
{
	"class": "fold_button_control",
	"settings": ["Seti_dark_fold_button"],
	"layer0.tint": [0, 0, 0]
},
```
and in my Preferences.sublime-settings:
```
{
	"Seti_dark_fold_button": true
}
```
Thanks in advance.

**Comment by ctf0** [comment]
Yeah sure, can u add the setting to the other fold options and send me a pr
?

**Comment by arturoSoto** [comment]
Done.
