### ISSUE TITLE
Extend theme color to window title bar

### ISSUE THREAD

**Issue by fathergoose** [ctf0/Seti_ST3#295]
Since build Build 3127, ST has [supported the ability](http://www.sublimetext.com/docs/3/themes.html#elements-windows) to change the color of the title bar on osx 10.10 and up. It would look really sharp to extend the Seti black to the title bar.

<img width="1680" alt="screen shot 2017-07-02 at 10 42 32 pm" src="https://user-images.githubusercontent.com/14184822/27777357-cd5b3d02-5f77-11e7-8d30-e3956fd5c9a4.png">
Here is the Seti color scheme with the Sublime Accessibility theme (one of the default themes) showing what the dark title bar looks like. Unfortunately, this theme is much less beautiful than your's .

I can submit a PR if you would prefer.

Thanks for the beautiful theme.

**Comment by ctf0** [comment]
i focken LOOOOOVE the new feature , but skining the theme to support both looks is very daunting and i dont have that much time like b4 , so if you can do it from ur end i would deeply appreciate it ❤️ .

**Comment by fathergoose** [comment]
Thoughts on which preference of the lighter or darker bar?


Lighter bar, darker text, Seti.sublime-theme
<img width="1435" alt="screen shot 2017-07-03 at 11 03 32 am" src="https://user-images.githubusercontent.com/14184822/27801549-3acf5c08-5fe4-11e7-9f03-96326ebbc704.png">
Darker bar, darker text, Seti.sublime-theme
<img width="1440" alt="screen shot 2017-07-03 at 11 04 28 am" src="https://user-images.githubusercontent.com/14184822/27801551-3bfd7394-5fe4-11e7-86fd-781e8a40919d.png">
Darker bar, darker text, Seti_org.sublime-theme
<img width="1436" alt="screen shot 2017-07-03 at 11 07 25 am" src="https://user-images.githubusercontent.com/14184822/27801552-3d6dd84a-5fe4-11e7-84df-cb0e21e2e5ee.png">
Lighter bar, darker text, Seti_org.sublime-theme
<img width="1436" alt="screen shot 2017-07-03 at 11 08 46 am" src="https://user-images.githubusercontent.com/14184822/27801553-3f1d3730-5fe4-11e7-9f77-ae4113617609.png">
Lighter bar, lighter text, Seti_org.sublime-theme
<img width="1437" alt="screen shot 2017-07-03 at 11 09 57 am" src="https://user-images.githubusercontent.com/14184822/27801554-41576854-5fe4-11e7-9efb-7039b061134b.png">

**Comment by fathergoose** [comment]
Also note the last one varies the color of the foreground text in the bar from the color of the text in the side bar to pure white. I chose to not go through all the combinations again with the bright white, you can use your imagination for now :)

**Comment by ctf0** [comment]
awesome 👍 

- for the bar it can follow the same color of file `tabset-background.png` & if possible just make an option for one accent and i will add the others "more of a guideline of what i should do"
- for the bar txt color, you can keep it to white for now then we can edit it later

**Comment by fathergoose** [comment]
Sounds good.

Is there any reason for the accent color to affect color of the title bar? I was assuming not, and achieved what you saw by adding 
```json
    {
        "class": "title_bar",
        "fg": [170, 170, 170],
        "bg": [13, 16, 17]
    }
```
(or some variation of that) to the bottom of the seti.sublime_theme and set_org.sublime_theme files.

Thus not having any need to duplicate things for each accent setting. Am I understanding correctly? Would you prefer I do this a different way?

**Comment by ctf0** [comment]
i honestly cant remember why i used images instead of the code, but if you are achieving the same result as the original then carry on 🍺
