### ISSUE TITLE
Folder carets not displaying for Seti or Seti_orig in Windows 10, ST3 build 3126

### ISSUE THREAD

**Issue by sebastianiorga** [ctf0/Seti_ST3#297]
![image](https://user-images.githubusercontent.com/7011617/29182199-e55dee08-7df5-11e7-8095-365a8041f7bf.png)

Windows 10, Version 10.0.15063 Build 15063

User settings are 
```JSON
{
	"bold_folder_labels": true,
	"caret_extra_bottom": 3,
	"caret_extra_top": 3,
	"caret_extra_width": 2,
	"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
	"font_size": 13,
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"overlay_scroll_bars": "enabled",
	"tab_size": 2,
	"theme": "Seti_orig.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true
}
```

Had some other custom themes that didn't show carets either. Default ST3 themes show them just fine.

**Comment by ctf0** [comment]
unfortunately i have either mac or w7 to test with, so not sure how i can help u 😞

**Comment by sebastianiorga** [comment]
:( no worries, totally understand. Maybe someone that uses it in W10 comes along and knows how to fix it. 

It was working fine ... last year? 6 months ago? I normally use ST3 in Ubuntu, just recently opened it up again in Windows to use with a steam custom game project and boom no carets.

No errors in Sublime console. Any ideas how I might debug this? Again, totally understand if you can't help.

Thanks for the work on the theme! Been using and loving it for ages in linux land.

**Comment by ctf0** [comment]
actually i think what u r looking for is `"Seti_show_group_arrows": true`

**Comment by sebastianiorga** [comment]
And it works. Thanks, dude!
