### ISSUE TITLE
New version of Seti

### ISSUE THREAD

**Issue by kylebebak** [ctf0/Seti_ST3#298]
The `Widgets` directory is missing in this latest version. This has changed background colors in the quick panel and find bar text fields. They used to have a nice dark-gray background.

## Before
<img width="586" alt="screen shot 2017-09-08 at 11 25 51 am" src="https://user-images.githubusercontent.com/1524088/30221379-9e24c990-9488-11e7-87ff-8bbcbec70013.png">

## Now
<img width="600" alt="screen shot 2017-09-08 at 11 24 10 am" src="https://user-images.githubusercontent.com/1524088/30221290-553afd62-9488-11e7-86dd-eb644000d4a1.png">

Here's `package-metadata.json`.

```
{"sublime_text": ">=3000", "platforms": ["*"], "description": "Seti_UI Port for ST3.", "version": "17.1.1", "url": "https://github.com/ctf0/Seti_ST3", "dependencies": []}
```

**Comment by ctf0** [comment]
actually i have removed a while ago, can u give me ur current seti settings ?

**Comment by kylebebak** [comment]
@ctf0 
Thanks for the quick response =)

**Comment by ctf0** [comment]
https://github.com/ctf0/Seti_ST3/releases/tag/v17.1.2
