### ISSUE TITLE
The theme makes about box font unreadable and hides the search box

### ISSUE THREAD

**Issue by sebastian-code** [ctf0/Seti_ST3#301]
> What version of ST are you using? (nothing lower than 3103).

Sublime Text 3 Build 3143

> Have you restarted ST after you installed the theme?

Yes

> If you still have bad render, have you removed the cache folder (found right next to the packages folder)?

Yes

> Extra Info

Once you select the theme Seti, it changes the font color inside the _About Sublime Text_ to white, what makes it unreadable and changes the search box color in the interactive drop-down command list to the same color of the background, which hides the box, harming the UX flow because you're unable to see it.

**Comment by ctf0** [comment]
can u show me a screen shot ?

**Comment by sebastian-code** [comment]
![captura de pantalla de 2017-11-02 05-41-25](https://user-images.githubusercontent.com/5254850/32321872-9e029f68-bf90-11e7-9f65-20a6403d3c33.png)

For additional information, I'm using Sublime in Ubuntu Linux, with Gnome Desktop.

**Comment by sebastian-code** [comment]
I apologize for the photo quality, but the drop down menu feature changes when any key is pressed, so I'm unable to take a proper screen shot, so, with the phone it goes.
![img_20171102_113919](https://user-images.githubusercontent.com/5254850/32338635-5cd3b300-bfc3-11e7-8ff7-296ebbb39d9a.jpg)

**Comment by ctf0** [comment]
i dont have this issue on mac or window, but i will recheck again, can u try applying one of the accents and see if it fixes the issue ?

**Comment by sebastian-code** [comment]
If I change to Seti_org, it changes the _About Sublime Text_ color scheme like this:
![captura de pantalla de 2017-11-02 15-55-25](https://user-images.githubusercontent.com/5254850/32349824-522e08e2-bfe6-11e7-938c-41899e8a815a.png)

But when I return to the Seti accent, it return to the unreadable color scheme from the first picture, but it doesn't fix the search box issue.

**Comment by ctf0** [comment]
okay, can u show the search box as well ?

**Comment by sebastian-code** [comment]
![img_20171102_171757](https://user-images.githubusercontent.com/5254850/32353235-92ad3fb2-bff2-11e7-97e4-437f697cc513.jpg)
Still the same issue using the Seti accent.

**Comment by ctf0** [comment]
this is the quick overlay box, and this is how it should be, not sure what is the problem with it

**Comment by sebastian-code** [comment]
Ah, ok, wrong term then. If that's the way it is intended, then is ok with me, I though than, as the text box has no contrast, that makes it difficult to notice it above the list of options and I wasn't sure of that and because I was having the other issue I put them both together.

**Comment by ctf0** [comment]
okay np, i have fixed the about dialog
you are correct, the overlay box have no/small contrast but i couldn't find a suitable color for it, if u have a suggestion am all ears

**Comment by sebastian-code** [comment]
What about the same color used by the theme to highlight the available choices in the overlay box list?

**Comment by ctf0** [comment]
u mean yellow, good idea, but i think it will make more sense if used with the accents

**Comment by sebastian-code** [comment]
To be truthful, than topic fall far beyond my abilities, I wouldn't be able to suggest a good matching color, perhaps the same tone of gray used to color the non active tabs.

**Comment by ctf0** [comment]
will see what i can do about it latest, thanx for the about box issue headsup.
