### ISSUE TITLE
double click the ST topbar can`t expand or zoom the editor

### ISSUE THREAD

**Issue by javasgl** [ctf0/Seti_ST3#302]
> What version of ST are you using? (nothing lower than 3103).

version 3.0 Build 3143

> Have you restarted ST after you installed the theme?

yes, restarted.

> If you still have bad render, have you removed the cache folder (found right next to the packages folder)?

yes

> Extra Info "attaching a screen shot would be very helpful"

the topbar is dark~ AND CANT`T expand by double click
![image](https://user-images.githubusercontent.com/5222868/33226913-b7f61c98-d1d2-11e7-822f-2ed708d6d9bb.png)

**Comment by ctf0** [comment]
the adaptive theme doesnt allow this "maybe u should open a ticket on ST repo/forum for that"

still, using `"Seti_use_system_title_bar": true,` would solve that for u.

**Comment by javasgl** [comment]
thanks! it works~
