### ISSUE TITLE
not working !

### ISSUE THREAD

**Issue by Adam-Human** [ctf0/Seti_ST3#303]
**i did all steps as u said and clean the cach + i restart sublime many times 
and even uninstall and install the package again many times and still not showing up** 

![5659](https://user-images.githubusercontent.com/34262746/33593923-ecaae4d4-d991-11e7-9437-90a538d394b4.jpeg)

**>> i'm using sublime text 3 . build : 3143 which is the last**

**Comment by ctf0** [comment]
have u tried to activate the theme from sublime `UI: Select Theme` ?

what does the console says ?

**Comment by Adam-Human** [comment]
**_it dosnt appear on UI theme List :_**

![150154](https://user-images.githubusercontent.com/34262746/33611200-cdf6ad5c-d9cd-11e7-931e-e29e0de56276.jpeg)


_**The Console : >**_
> ***
> Traceback (most recent call last):
> reloading plugin A File Icon.A File Icon
> generating meta info summary
> reloading settings Packages/User/Package Control.sublime-settings
> reloading settings Packages/User/Preferences.sublime-settings
>Unable to open .../Sublime Text 3/Packages/A File Icon/.sublime/A File Icon.sublime-settings
>Unable to open .../Sublime Text 3/Packages/User/A File Icon.sublime-settings
> ...
> A File Icon: Please restart Sublime Text for the applied icons to take effect ...
> ...
> generating syntax summary
> generating syntax summary
> ***
**_. end of Console_**

**Comment by ctf0** [comment]
i think u have something wrong with your setup, because those 2 in the screen shot are sublime default themes.

**Comment by Adam-Human** [comment]
i Even Install "Material Theme" to see if the problem is in my setup 
and "Material Theme" work normal as u can see : 
![00016](https://user-images.githubusercontent.com/34262746/33615913-a0ff8fd6-d9db-11e7-9a3b-7c51558f93c3.png)

the issue is the icons dosnt appear .

**Comment by ctf0** [comment]
sorry i cant help :disappointed:

**Comment by Adam-Human** [comment]
if you know some users here who could help us , plz tag them in this issue :|

**Comment by ctf0** [comment]
maybe u can try posting on the sublime forum itself about not being able to set the default themes.

**Comment by Adam-Human** [comment]
loool hahahaha , i drag & drop the whole folder into the editor not only one file and its work , the icons show up

![screenshot_20171205192230](https://user-images.githubusercontent.com/34262746/33623559-b46fe24e-d9f1-11e7-9c1c-d0f7c5677831.png)


we where dump to not think about that hihihihi XD 

now plz put in the installation info that you need to drag all the folder of project to see the icons X)
so if anyone else meet this issue he could know how its work

**Comment by ctf0** [comment]
as those icons not related to seti, i believe u r in the wrong place.

**Comment by Adam-Human** [comment]
i mean seti still there in the package but the "Material theme" package write his icons over them thats it , i remove "Material theme" and seti icons show up
