### ISSUE TITLE
seti_ui breaks sublime text, black window "osx mojave"

### ISSUE THREAD

**Issue by webrender** [ctf0/Seti_ST3#304]
> What version of ST are you using? (nothing lower than 3103).

3176

> Have you restarted ST after you installed the theme?

Yes

> If you still have bad render, have you removed the cache folder (found right next to the packages folder)?

Yes

> Extra Info "attaching a screen shot would be very helpful"

<img width="1330" alt="screen shot 2018-10-19 at 10 47 28 am" src="https://user-images.githubusercontent.com/189682/47235128-ed9a6180-d38c-11e8-97ce-3eb827f943d3.png">

removing the package, or resetting the theme in preferences, fixes ST.

**Comment by ctf0** [comment]
am using it on windows with v3176 and mac with v3180 and in both the theme is working fine, check the console to see what exactly is causing this

**Comment by webrender** [comment]
unfortunately when i select the theme, everything disappears, including the console.  is there a way i can open the console output in another application?

**Comment by ctf0** [comment]
as far as i know each window have its own console, so opening another window with a different theme wont help.

**Comment by webrender** [comment]
upon doing some more experimentation, this appears to be linked to the `title_bar` properties - removing all references from the theme file fixes the functionality. 

When I tried specifying the title bar color in another theme, the same thing happened, so it seems like this is related to ST or possibly Mac OS, and not the seti theme. Feel free to close this unless you'd like to keep it open for others experiencing similar issues.

**Comment by webrender** [comment]
`"Seti_use_system_title_bar": true,` fixed it for me. not sure what's going on there, i just performed a system update before this happened so it may be related. (`osx 10.14.1 Beta (18B67a)`)

**Comment by webrender** [comment]
more info + fix here: https://forum.sublimetext.com/t/sublimetext-3180-turned-into-totally-dark-after-mojave-upgraded-to-10-14-1-beta/39901/10

> By editting the preference file to set following:
> `"gpu_window_buffer": false,`
> will make sublimetext work for now. The file was located at Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings

**Comment by wongyongcheng** [comment]
thanks
