### ISSUE TITLE
Seti UI在3176版本下面不兼容。

### ISSUE THREAD

**Issue by wongyongcheng** [ctf0/Seti_ST3#305]
安装Seti UI主题并使用后，sublime text 启动后黑屏，编辑框位置所有内容均不可见。[https://imgsa.baidu.com/forum/w%3D580/sign=d00606a6bf119313c743ffb855390c10/6b422234349b033bd8f034be18ce36d3d439bdc7.jpg](url：https://imgsa.baidu.com/forum/w%3D580/sign=d00606a6bf119313c743ffb855390c10/6b422234349b033bd8f034be18ce36d3d439bdc7.jpg)

**Comment by ctf0** [comment]
in english plz ?

**Comment by wongyongcheng** [comment]
After installing the Seti UI theme and using it, the sublime text is black after startup, and all the contents of the edit box are not visible.
