### ISSUE TITLE
Vim (Vintage) mode caret visibility issue

### ISSUE THREAD

**Issue by yavorski** [ctf0/Seti_ST3#306]
Hi,

The block caret in vim (vintage) mode became almost invisible, or very very hard to see.
I am not sure if the issue is related with SetiUI or Sublime Text itself, but it arised lately with the recent updates of both.
Within recent updates I mean 3,4 months or so.

These are the settings I use:

```json
{
  "theme": "Seti_orig.sublime-theme",
  "color_scheme": "Packages/Seti_UX/Seti.tmTheme",
  "Seti_SB_bright": true,
  "Seti_tabs_small": true,
  "caret_extra_top": 2,
  "caret_extra_bottom": 2,
  "caret_extra_width": 2,
  "default_line_ending": "unix",
  "draw_white_space": "all",
  "font_size": 10.42,
  "font_face": "Operator Mono Medium",
  "highlight_line": false,
  "highlight_modified_tabs": true,
  "indent_guide_options": [ "draw_active" ],
  "margin": 4,
  "line_padding_bottom": 2,
  "show_line_endings": true,
  "vintage_ctrl_keys": true,
  "vintage_start_in_command_mode": true,
  "ignored_packages": []
}
```

More info:

* OS: ubuntu, debian, windows
* Sublime Text 3 version 3.2 build 3200
* Restarted multiple times after the theme installation
* Deleted the cache folder found right next to the packages folder
* Screenshot is attached below

Question?

Is somehow possible to increse the visiblity of the block cursor in vim (vintage) mode?
Any ideas are greatly appreciated.

Thanks in advance!

![seti-ui-caret-vim-hard-to-see](https://user-images.githubusercontent.com/3436517/54767621-38ebc100-4c06-11e9-9bea-5737f00df61f.png)

**Comment by AlexVentura** [comment]
I think it is not related to the them, because I have the same problem and I do not use `Seti_ui`. I wonder it can be fixed soon because it is hard to work this way almost invisible cursor!

**Comment by ctf0** [comment]
@yavorski i cant help as i dont use vim mode but try with other themes to 2xcheck what @AlexVentura said and see if its global or specific to seti

**Comment by yavorski** [comment]
Hi,

I tested with all themes and color schemes I have.
In most of them the issue is presented, but there are some themes in which the caret is fine.
There were some themes in which the caret changed its (bg)color to blue. (screenshot is attached below)
This makes me believe that there is indeed a way to change the caret color.
I just don't know how.

![sublime-text-blue-caret](https://user-images.githubusercontent.com/3436517/54919381-5623d680-4f09-11e9-8fe7-7e21a4f737c5.png)

**Comment by yavorski** [comment]
Hi, after some research in sublime forums, I was able to find that is possible to change the block caret in the `some-color-scheme.sublime-color-scheme` file, but I am unable to find `*.sublime-color-scheme` file for the Seti UI color scheme.

I opened the `Mariana.sublime-color-scheme` that is shipped with sublime text itself (opened with `PackageResourceViewer`) and added `"block_caret": "yellow"` in the `"globals"` section and it worked:

```json
"globals": {
  "caret": "yellow",
  "block_caret": "yellow",
}
```

Does `Seti_UI` color scheme have a `*.sublime-color-scheme` file, because I am unable to find it?

If not, is there an alternative file where we can add this settings.

Link for reference [Sublime Text Color Schemes](http://www.sublimetext.com/docs/3/color_schemes.html) -> search for `block_caret`.

Thanks in advance!

**Comment by ctf0** [comment]
the `sublime-color-scheme` is a scheme file "for syntax highlight" but seti_ui is a theme "for sublime app look", so what u want is to add the setting to the whatever scheme u r using.

**Comment by yavorski** [comment]
Hi

Thank you for the quick responses on this issue!

I am using both `Seti_UI` and `Seti_UX` packages.
These are settings I am using in my sublime text preferences:

```json
{
  "theme": "Seti_orig.sublime-theme",
  "color_scheme": "Packages/Seti_UX/"
}
```

After looking at [Seti_UX](https://github.com/ctf0/Seti_UX) repository
it seems `Seti_UX` does not provide a `*.sublime-color-scheme` file which is the newer format
for sublime text 3 color schemes, it provides only the legacy syntax with `Seti.tmTheme` file.

I also found a related issue in the in the `Seti_UX` repository.

* [Convert to `.sublime-color-scheme`](https://github.com/ctf0/Seti_UX/issues/40)

However I found that we can add these settings in the `Seti.tmTheme` file and fix the `block_caret` issue:

```
<key>block_caret</key>
<string>#ffd200</string>
```

I made a pull request with the settings above.
This will make the carret in vim mode the same color as default caret:

Please take a look at it [https://github.com/ctf0/Seti_UX/pull/47](https://github.com/ctf0/Seti_UX/pull/47);

Thanks again for your help and cooperation!

**Comment by ctf0** [comment]
PR merged, thanx
