### ISSUE TITLE
Port of seti_orig to VS Code?

### ISSUE THREAD

**Issue by Kaos-Industries** [ctf0/Seti_ST3#308]
Hey there, 

I apologise if this isn't the right place for this, but I've been using your `Seti_orig` as a UI theme for almost 5 years in ST3, until I recently moved to VS Code after being recommended it by so many people. VS Code is a more powerful editor, and there's a lot that I like about it, but the biggest thing I'm missing is a decent-looking interface, and I was wondering whether there's any chance of a port of `Seti_orig` over to VS Code? 

There's a port currently available in VS Code's extensions repo called `theme_seti`, but that looks and behaves so differently to yours that it feels like a different theme. 

Thanks in advance, I'd really appreciate a response.

**Comment by ctf0** [comment]
yeah i understand what u r after but the issue is from the first time i ported the scheme from atom to sublime i didnt update it all, which will actually look different through the versions of ST it self.

also vscode scopes are more stricter than what ST offer, however if u still need it u may try to port it ur self by comparing the 2 editors scheme against each other "at least thats what i did when i was porting it the first time"

**Comment by ctf0** [comment]
actually i would like to get more involved into the ui scene of vscode as i myself has joined the gang too, but my time is very busy due to job/family/etc.. , still if u have the time & persistence to carry on with the idea i will be more than happy to help with any questions u may have :trophy:

**Comment by Kaos-Industries** [comment]
Unfortunately, I don't have much time myself nowadays, and in addition know very little about theming and programming, so it would take me double the time. I'm happy to make myself available for testing if you ever do get around it though. As for those items you mentioned, they're not of particular importance to me so long as the rest of the UI broadly looks like the seti_orig theme does.

**Comment by ctf0** [comment]
i've made a port and it will be [available soon](https://github.com/ctf0/Seti_UX-vscode), thanx for the suggestion

**Comment by Kaos-Industries** [comment]
Thanks so much for your work, I look forward to seeing it
