### ISSUE TITLE
No icons on the sidebar

### ISSUE THREAD

**Issue by kadhim-alawi** [ctf0/Seti_ST3#33]
I am using the last build 3065 of ST 3 and I follow the installation instructions but couldn't get the sidebar icons loaded, any idea?

**Comment by mladenp** [comment]
I got the same problem, no icons are shown. 
I am using Themr and i did create *Theme - Default* dir inside Packages dir but nothing.

**Comment by ctf0** [comment]
@mladenp clean the cache and remove the theme, then reinstall it again

**Comment by mladenp** [comment]
I tried adding theme again but don't know how to clean ST cache?

**Comment by ctf0** [comment]
next to packages folder there is cache inside it u will find the cached packages.

**Comment by mladenp** [comment]
Nope, cache folder doesn't exist anywhere. Weird?

**Comment by ctf0** [comment]
yeap, cache should be where ur sublime text packages are
