### ISSUE TITLE
Icons not showing up in ubuntu 14.04

### ISSUE THREAD

**Issue by awebdeveloper** [ctf0/Seti_ST3#87]
I have Ubuntu 14.04 with ST3 v3065

I downloaded the theme from package control. Set theme to Seti_monokai. Then copied EXT contents to User folder. And restarted ST3. But not sure why icons dont show up in sidebar.

![screenshot from 2015-01-01 22 12 58](https://cloud.githubusercontent.com/assets/1593429/5592722/d235db68-9204-11e4-8d9a-6062315677b4.png)

**Comment by ctf0** [comment]
i can see there are some icons showing and thats because u have `Theme - Default/icons` which u should give it a different name because whatever is in this folder will override anything else.

**Comment by completit** [comment]
I'm having the same issue on Windows 7 x64, no icon changes.
Do you think that changing the name of `Theme - Default/icons` could fix it ?

**Comment by ctf0** [comment]
@completit u r right and wrong ,the `Theme - Default/icons` are found in the packages folder if u dont know about it then ignore it ,2nd the icons should work out of the box without doing anything.

**Comment by rvinay88** [comment]
The icons did not work out of the box. I am using ST3 3083 and had to follow the [link](http://www.sublimetext.com/forum/viewtopic.php?p=60086#p60086) to get it working. But now it's working. Thanks for all the hardworkd and sharing!
