### ISSUE TITLE
Small UI Tweaks for better UX

### ISSUE THREAD

**Issue by jwilkinson** [ctf0/Seti_ST3#88]
I would like to suggest the reduction in spacing between folders, we have a lot of nested folders in our project would be great to see the space reduced significantly to be able to navigate the tree better.

Second I would like to recommended the base theme have lighter line numbering, it's nearly impossible to see the line number right now.

![toodark2](https://cloud.githubusercontent.com/assets/378068/5597544/2a2922b8-9272-11e4-9977-b75da0e23af7.png)

**Comment by ctf0** [comment]
u mean the padding ,and its already added check (Seti_sb_small_padding / Seti_sb_big_padding) for the gutter color ,u r right and its now changed ,if u have a better color plz tell me.

**Comment by jwilkinson** [comment]
Don't be so quick to the punch, your setting is not what I am talking about.

The left padding not the padding around the whole item, see how deep the tree indents
![toobig](https://cloud.githubusercontent.com/assets/378068/5614337/30818abc-94be-11e4-97e4-6d82d779df9b.png)


As for the line numbering you could use the same colour as the folders #38695d

**Comment by ctf0** [comment]
ahaaa ,do u prefer that all have the same indentation ? , if u have something else in mind tell me

**Comment by jwilkinson** [comment]
I the tree indenting is key to ux flow but its just too much id try 20px
increments

**Comment by ctf0** [comment]
download the latest commit and check if thats what u want
u have 2 options `Seti_sb_tree_med` & `Seti_sb_tree_small`

**Comment by jwilkinson** [comment]
Way better, and now I realize how gigantic my project is. Is there an option for the parents to like 5px apart compounded? It's still a ton of real estate at 20px but for smaller projects I think thats a nice default.

**Comment by ctf0** [comment]
can u show me a ss with what u mean ?

**Comment by jwilkinson** [comment]
I'm just saying that maybe there should be a Large: 45px, Medium: 20px, and Small 5px of nesting after each drop down. Just make small really small so people with big projects don't have to scroll as much sideways and can have a smaller sidebar in sublime

**Comment by ctf0** [comment]
(Seti_sb_small_padding / Seti_sb_big_padding) is exactly what u want.

**Comment by jwilkinson** [comment]
No that I already have, what you just added "Seti_sb_tree_small": ture should be a lot smaller less left padding, than currently, make it like really really small like 5px

**Comment by jwilkinson** [comment]
Also even though its set to 10 there is still 20px from left to right on each tree drop down. 
![smaller](https://cloud.githubusercontent.com/assets/378068/5633846/1a278000-95a9-11e4-939d-26ba41ccfe2e.png)

See like after the Red, a deep tree wont be so far to the left of the edge of the screen, less whitespace

**Comment by jwilkinson** [comment]
The size of the tree indentation

**Comment by ctf0** [comment]
i add anew tiny one ,check and tell me.

**Comment by jwilkinson** [comment]
"Seti_sb_small_padding" has stopped working when Tiny is turned on, Ill see if I can figure out sublime themeing haha

**Comment by jwilkinson** [comment]
````
{
        "class": "sidebar_tree",
        "settings": ["Seti_sb_tree_tiny"],
        "indent": 5,
        "row_padding": [5,5],
        "indent_offset": 15,
    },
````

**Comment by ctf0** [comment]
is that exactly what u want ?

**Comment by jwilkinson** [comment]
Yep! Now my tree is managable

![2015-01-06_14-01-17](https://cloud.githubusercontent.com/assets/378068/5634277/9720606a-95ac-11e4-8b10-5834c804a8a5.png)

**Comment by ctf0** [comment]
its now called `miny`

**Comment by NekR** [comment]
Sidebar options does not work for me now, it's always default size. Build 3065.

**Comment by ctf0** [comment]
what are the theme options u added to ur settings file ?

**Comment by NekR** [comment]
@ctf0
```json
{
	"Seti_ClosedFolder_dots": true,
	"Seti_sb_small_padding": true,
	"Seti_sb_tree_tiny": true,
	"Seti_tabs_small": true,
	"caret_extra_width": 2,
	"color_scheme": "Packages/Seti_UI/Scheme/Seti_orig.tmTheme",
	"draw_white_space": "all",
	"fade_fold_buttons": false,
	"font_size": 12.0,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_active"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 0,
	"minimap_scroll_to_clicked_text": false,
	"rulers":
	[
		80,
		100,
		120
	],
	"save_on_focus_lost": true,
	"shift_tab_unindent": true,
	"spell_check": true,
	"tab_size": 2,
	"theme": "Seti.sublime-theme",
	"translate_tabs_to_spaces": true,
	"word_wrap": true
}
```

This is my whole settings file. Any of "Seti_sb_tree_*" does not work for me.

**Comment by ctf0** [comment]
try to set `Seti_sb_small_padding: false` and it should fix ur prob.

**Comment by NekR** [comment]
It does not helps, may be something wrong with my particular Sublime installation. I will be able to record video to demonstrate the problem later.

**Comment by ctf0** [comment]
the thing is ,both
```
"Seti_sb_small_padding": true,
"Seti_sb_tree_tiny": true,
```
use a specific setting ,thats why u should use one of them not both at the same time
