### ISSUE TITLE
Seti GUI  is gone

### ISSUE THREAD

**Issue by JKdreaming** [ctf0/Seti_ST3#90]
Don't know why, but I opened sublime and the seti package was being ignored and when I reactivated it I lost your awesome gui design.  Can you help me get it back? I've uninstalled and reinstalled and used these settings:

{
	"Seti_ClosedFolder_dots": true,
	"Seti_ClosedFolder_remove": true,
	"Seti_ClosedFolder_same": true,
	"Seti_SB_big": true,
	"Seti_SB_bright": true,
	"Seti_SB_med": true,
	"Seti_mouse_wheel_tabswitch": true,
	"Seti_no_bar_undertabs": true,
	"Seti_rainbow": true,
	"Seti_sb_big_padding": true,
	"Seti_sb_small_padding": true,
	"Seti_sb_tree_med": true,
	"Seti_sb_tree_miny": true,
	"Seti_sb_tree_small": true,
	"Seti_sb_tree_tiny": true,
	"Seti_tabs_med": true,
	"Seti_tabs_small": true,
	"caret_extra_bottom": 3,
	"caret_extra_top": 3,
	"caret_extra_width": 2,
	"color_scheme": "Packages/Seti_UI/Scheme/Seti.tmTheme",
	"dictionary": "Packages/Language - English/en_US.dic",
	"highlight_line": true,
	"ignored_packages":
	[
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"margin": 3,
	"overlay_scroll_bars": "enabled",
	"spell_check": true,
	"theme": "Default.sublime-theme",
	"word_wrap": true
}

_______

Am I doing something wrong?

Thank you,
Joshua

**Comment by ctf0** [comment]
actually u shouldn't be enabling all the theme settings at once ,i think i mentioned that in the readme, secondly the enabled theme is the `"theme": "Default.sublime-theme"` ,u need to change it to the seti theme file instead because the gui have 2 parts (scheme & theme)

**Comment by JKdreaming** [comment]
Sorry that was after a lot of tinkering so I probably forgot to switch that back.  I just changed it like 10 times in a row and in the tradition of Spinal Tap it finally worked on 11.

Thank you,
Joshua

**Comment by ctf0** [comment]
haha ,ST is crazy.
