### ISSUE TITLE
Add support for GitGutter

### ISSUE THREAD

**Issue by ClementParis016** [ctf0/Seti_ST3#91]
I really like using GitGutter Sublime package (https://github.com/jisaacks/GitGutter) to see diffs in versionned files, but unfortunately Seti seems to don't support it since it doesn't show the diffs.

Is it doable to add support for this in Seti? It would be so cool :)

**Comment by ctf0** [comment]
i believe all of schemes have GG & Diff support except Seti which didn't ,so i updated ,i don't use any but check now and tell me if this fix ur issue.

**Comment by ClementParis016** [comment]
Thank you for the quick update!

Currently, I can't see anything changed, maybe it's due to my settings?

User settings
```json
{
	"Seti_ClosedFolder_same": true,
	"Seti_tabs_small": true,
	"bold_folder_labels": true,
	"caret_extra_width": 2,
	"caret_style": "phase",
	"color_scheme": "Packages/Seti_UI/Scheme/Seti.tmTheme",
	"font_face": "Source Code Pro",
	"font_size": 11,
	"highlight_line": true,
	"ignored_packages":
	[
		"SublimeLinter",
		"jQuery",
		"Vintage"
	],
	"overlay_scroll_bars": "enabled",
	"scroll_speed": 5.0,
	"tab_size": 2,
	"tabs_small": true,
	"theme": "Seti.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true
}
```

PS: I'm running ST3 on Windows 8.1, if this helps

**Comment by ctf0** [comment]
no the settings got nothing to do with the syntax HL ,the problem is i don't know how to use `Gitdiff` with ST as i use another app just for that but anyway try with other schemes and tell me which do work ,maybe i can come up with a solution.

**Comment by ClementParis016** [comment]
So, I guess what you're looking for is just there: https://github.com/jisaacks/GitGutter#icon-coloring

**Comment by ctf0** [comment]
all 3 schemes are supported ,
open any of them and u will find the same syntax from the link u provided ,if the HL works in any other scheme so it should with this one too.

**Comment by ClementParis016** [comment]
Ok then I think it's a problem with my own environment, probably with Git config, because it doesn't work with any scheme for me. Maybe someone else could confirm it works now?

**Comment by ctf0** [comment]
try to open an issue on `GitGutter` and check what is the recommended settings and start from there as this is clearly not a HL issue.

**Comment by ClementParis016** [comment]
I just came accross the problem: Git wasn't in my PATH, so GitGutter couldn't access it. I've added the Git bin folder to PATH and now it works perfectly.

Thanks for the help.
