### ISSUE TITLE
Missing Seti_mouse_wheel_tabswitch option

### ISSUE THREAD

**Issue by ezrepotein** [ctf0/Seti_ST3#96]
Recently there was an additional option available:
```
{
  "Seti_mouse_wheel_tabswitch": true
}
```
It allowed to switch tabs using mouse wheel. The same behavior is implemented in default sublime themes. It was very useful and consistent with Ubuntu environment which uses it throughout the system. Why was it removed, could you bring it back?

My Seti_UI version: 2015.02.05.02.30.27

**Comment by ctf0** [comment]
its changed to `mouse_wheel_tabswitch": true`
