### ISSUE TITLE
Seti_UI and Syntax higlighting for Sass conflicts

### ISSUE THREAD

**Issue by mariojankovic** [ctf0/Seti_ST3#97]
Seti_UI is def the best sublime theme out there. The only issue I'm having with it is that it's constantly trying to revert the theme to default because of some conflicts with the above mentioned package. Also, when trying to globally apply syntax highlighting for Sass sublime is trying to use Seti's syntax highlighter.

My sublime version is 3065.

**Comment by ctf0** [comment]
can u write some steps to reproduce what u r currently have ?

**Comment by mariojankovic** [comment]
Downloaded clean ST3, installed Package manager > Seti_UI > Syntaxt Higlighting for Sass. After that I can't set this syntax as default (it always reverts to the Seti_UI syntax) and at some point even the whole theme reverts to the Default theme (after a day or two).

**Comment by ctf0** [comment]
the last update of theme should have a new sub_menu in the syntax panel as `Seti_UI`,try to manually install from this repo and try again ,don't forget to clear the cache folder.

**Comment by mariojankovic** [comment]
Still the same. I deleted the cache folder, even tried downloading sublime again. Nothing helps. The only time this thing works is when I manually delete the SCSS/Sass tmLanguage files and set "Syntax higlighint for sass" as my main syntax highlighter because the default Seti_UI highlighting doesn't look good (it's missing proper BEM syntax highlighting, like this: http://i.imgur.com/FfDIMpD.png).

**Comment by ctf0** [comment]
lets try something else ,if u got the latest version of the theme u will find a `scss&sass` files inside folder call `Lang` remove those 2 files and try again ,they are basicly there for displaying the right icon but i believe the package u r using have this covered already.

**Comment by mariojankovic** [comment]
Yes, I've done that as described above. The two .tmTheme files are located inside the Prefs/Langs folder. Once I delete them all seems fine, until Package manager decides to update the theme and reverts everything to it's default state (restoring these two files). Can I somehow disable updates for Seti_UI via Package manager?

**Comment by ctf0** [comment]
yeah i know how frustrating that is, PC has became more and more of a naggy B*** ,
anyway manually add `Seti_UI` to the `auto_upgrade_ignore` in ur user-settings file.

**Comment by mariojankovic** [comment]
Great. This should work I guess: http://i.imgur.com/1IkZhD2.png
Thanks for your help!

**Comment by ctf0** [comment]
np ,glad i could help ,btw check the other HL seti_ux which have å better support over the current.

**Comment by TheDutchCoder** [comment]
This "hack" doesn't seem to work anymore. Did something change?

**Comment by ctf0** [comment]
@TheDutchCoder can u tell me exactly what u r facing atm ???

**Comment by TheDutchCoder** [comment]
I've added the package to my ignore list, but with a new release it keeps adding back the Sass language files, causing the conflict with Syntax Highlighting for Sass.

Not sure what's happening in this theme, but it keeps resetting the extension association back to Seti->Sass, instead of whatever I set as the default highlighting.

**Comment by ctf0** [comment]
does the `auto_upgrade_ignore` happens only with this package or with others too ???

**Comment by TheDutchCoder** [comment]
It's the only package in there so I'm not sure.
Obviously it's not working ;-)

Would it be an option to simply not auto-set the syntax highlighting in this theme when another one is already selected?

**Comment by ctf0** [comment]
Sadly something like that is handled by ST not the theme :(
